#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_MONIT_SERVICE_NUT_CONFIG=${OMV_MONIT_SERVICE_NUT_CONFIG:-"/etc/monit/conf.d/openmediavault-nut.conf"}
OMV_MONIT_SERVICE_NUT_MODE=${OMV_MONIT_SERVICE_NUT_MODE:-"active"}

rm -f ${OMV_MONIT_SERVICE_NUT_CONFIG}
[ "$(omv_config_get "//services/nut/enable")" != "1" ] && exit 0

if [ "standalone" = "$(omv_config_get "//services/nut/mode")" ]; then
cat <<EOF > ${OMV_MONIT_SERVICE_NUT_CONFIG}
check process nut-server with matching upsd
  group nut
  start program = "/bin/systemctl start nut-server"
  stop program = "/bin/systemctl stop nut-server"
  mode ${OMV_MONIT_SERVICE_NUT_MODE}
EOF

# Disable event notifications.
xmlstarlet sel -t -m "//system/email" \
  -i "enable = '1'" \
  -i "//system/notification/notifications/notification[id='monitprocevents']/enable = '0'" \
    -v "concat('  noalert ',primaryemail)" \
  -b \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_MONIT_SERVICE_NUT_CONFIG}
fi

cat <<EOF >> ${OMV_MONIT_SERVICE_NUT_CONFIG}

check process nut-monitor with matching upsmon
  group nut
  start program = "/bin/systemctl start nut-monitor"
  stop program = "/bin/systemctl stop nut-monitor"
  mode ${OMV_MONIT_SERVICE_NUT_MODE}
EOF

# Disable event notifications.
xmlstarlet sel -t -m "//system/email" \
  -i "enable = '1'" \
  -i "//system/notification/notifications/notification[id='monitprocevents']/enable = '0'" \
    -v "concat('  noalert ',primaryemail)" \
  -b \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_MONIT_SERVICE_NUT_CONFIG}
