version: "1.0"
type: route
data:
  url: "/system/updatemgmt/settings/sources/create"
  title: _("Create")
  notificationTitle: _("Created APT source.")
  component: omv-system-updatemgmt-settings-sources-form-page
