#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_PROFTPD_CONFIG=${OMV_PROFTPD_CONFIG:-"/etc/proftpd/proftpd.conf"}
OMV_PROFTPD_MODAUTH_DEFAULTROOT=${OMV_PROFTPD_MODAUTH_DEFAULTROOT:-"/srv/ftp"}
OMV_PROFTPD_MODAUTH_USEFTPUSERS=${OMV_PROFTPD_MODAUTH_USEFTPUSERS:-"off"}

xmlstarlet sel -t -m "//services/ftp" \
	  -o "<IfModule mod_auth.c>" -n \
      -o "  DefaultRoot ${OMV_PROFTPD_MODAUTH_DEFAULTROOT}" -n \
      -v "concat('  MaxClients ',maxclients)" -n \
      -i "maxloginattempts[. > '0']" -v "concat('  MaxLoginAttempts ',maxloginattempts)" -n -b \
      -i "requirevalidshell[. = '0']" -o "  RequireValidShell off" -n -b \
	  -i "requirevalidshell[. = '1']" -o "  RequireValidShell on" -n -b \
      -i "rootlogin[. = '1']" -o "  RootLogin on" -n -b \
      -o "  # This option is useless because this is handled via the PAM" -n \
      -o "  # pam_listfile.so module, so set it to 'off' by default." -n \
      -o "  UseFtpUsers ${OMV_PROFTPD_MODAUTH_USEFTPUSERS}" -n \
	  -o "</IfModule>" -n \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_PROFTPD_CONFIG}

# Modify /etc/ftpusers because root login is handled by the PAM
# pam_listfile.so module.
rootlogin=$(omv_config_get "//services/ftp/rootlogin")
if omv_checkyesno "${rootlogin}"; then
    # Allow 'root' to login.
    sed -i -e "s/^\(root\)/#\1/i" /etc/ftpusers
else
    # Deny 'root' to login.
    sed -i -e "s/^#\(root\)/\1/i" /etc/ftpusers
fi
