#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_PROFTPD_CONFIG=${OMV_PROFTPD_CONFIG:-"/etc/proftpd/proftpd.conf"}
OMV_PROFTPD_MODAUTHPAM_AUTHPAM=${OMV_PROFTPD_MODAUTHPAM_AUTHPAM:-"on"}
OMV_PROFTPD_MODAUTHPAM_AUTHPAMCONFIG=${OMV_PROFTPD_MODAUTHPAM_AUTHPAMCONFIG:-"proftpd"}

cat <<EOF >> ${OMV_PROFTPD_CONFIG}
<IfModule mod_auth_pam.c>
  AuthPAM ${OMV_PROFTPD_MODAUTHPAM_AUTHPAM}
  AuthPAMConfig ${OMV_PROFTPD_MODAUTHPAM_AUTHPAMCONFIG}
</IfModule>
EOF
