#!/bin/bash
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2014 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

xmlstarlet sel -t \
  -m "//system/fstab/mntent[not(contains(opts,'bind') or contains(opts,'loop'))]" \
	-v uuid \
	-i "position() != last()" -n -b \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc |
  while read uuid; do
	  fsname=$(omv_config_get "//system/fstab/mntent[uuid='${uuid}']/fsname")
	  dir=$(omv_config_get "//system/fstab/mntent[uuid='${uuid}']/dir")
	  # Modify spec field if it contains a UUID
	  if omv_isfsuuid "${fsname}"; then
		  fsname="UUID=${fsname}"
	  fi
	  # Print mount entry line.
	  xmlstarlet sel -t -m "//system/fstab/mntent[uuid='${uuid}']" \
		-o "${fsname// /\\\040} ${dir// /\\\040} " \
		-v "concat(type,' ',opts,' ',freq,' ',passno)" \
		${OMV_CONFIG_FILE} | xmlstarlet unesc
  done;
