#!/usr/bin/env dash
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2025 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.
MAILTO=""

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

omv_syslog_info "Checking for pending configuration changes."

# Notify the administrator if there are any configuration changes that
# need to be applied.
if omv_module_is_dirty; then
  msg="The configuration has been changed. You must apply the changes in order for them to take effect."
  omv_syslog_info ${msg}
  echo ${msg} | mail -E -s "Pending configuration changes" root
fi
