#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2023 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

MAILTO=""
OMV_BTRFS_ERROR_CHECK_ENABLED=${OMV_BTRFS_ERROR_CHECK_ENABLED:-"yes"}

# Exit immediately if Btrfs error checking is disabled.
! omv_checkyesno "${OMV_BTRFS_ERROR_CHECK_ENABLED}" && exit 0

omv_syslog_info "Performing an error check on Btrfs file systems."
findmnt --all --canonicalize --notruncate --uniq --noheadings --output SOURCE,TARGET --types btrfs |
    sort |
    while read row
do
     device=${row% *}
     mountpoint=${row#* }
     omv_syslog_info "Checking ${device} for errors ..."
     stats=$(btrfs device stats --check "${mountpoint}")
     if [ $? -ne 0 ]; then
         omv_syslog_warning "Errors were detected on the file system ${device}."
         # Ignore the file system notification settings because of the
         # importance of this message.
         (
             echo -e "Errors were detected on the Btrfs file system that is mounted under ${mountpoint}.\n";
             echo "${stats}"
         ) | mail -E -s "Errors were detected on the file system ${device}" root
     fi
done
