#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2016 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_PROFILE_PROXY_CONFIG=${OMV_PROFILE_PROXY_CONFIG:-"/etc/profile.d/10openmediavault-proxy.sh"}

xmlstarlet sel -t -m "//system/network/proxy" \
  -i "string-length(http/host) > 0" \
    -o "http_proxy=\"http://" \
    -i "string-length(http/username) > 0" \
	  -v "concat(http/username,':',http/password,'@')" \
	-b \
    -v "concat(http/host,':',http/port,'\"')" -n \
	-o "HTTP_PROXY=\$http_proxy" -n \
  -b \
  -i "string-length(https/host) > 0" \
    -o "https_proxy=\"https://" \
    -i "string-length(https/username) > 0" \
	  -v "concat(https/username,':',https/password,'@')" \
	-b \
    -v "concat(https/host,':',https/port,'\"')" -n \
	-o "HTTPS_PROXY=\$https_proxy" -n \
  -b \
  -i "string-length(ftp/host) > 0" \
    -o "ftp_proxy=\"ftp://" \
    -i "string-length(ftp/username) > 0" \
	  -v "concat(ftp/username,':',ftp/password,'@')" \
	-b \
    -v "concat(ftp/host,':',ftp/port,'\"')" -n \
	-o "FTP_PROXY=\$ftp_proxy" -n \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_PROFILE_PROXY_CONFIG}
