# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 60

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 90

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - pinned
  - security
  - "[Status] Maybe Later"

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: true

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: true

# Label to use when marking as stale
staleLabel: stale

pulls:
  # Comment to post when marking as stale. Set to `false` to disable
  markComment: >
    This pull request has been automatically marked as stale because it
    has not had any activity for 60 days. It will be closed if no further
    activity occurs for another 30 days.

    If you are a maintainer or core committer, please follow-up on this
    pull request to identify what steps should be taken by the author to move this
    proposed change forward.

    If you are the author of this pull request, thank you for your proposed
    contribution. If you believe this change is still appropriate, please
    ensure that any feedback has been addressed and ask for a code review.

  # Comment to post when removing the stale label.
  unmarkComment: >
    Thank you for updating this pull request. It is no longer marked as stale.

  # Comment to post when closing a stale Pull Request.
  closeComment: >
    This pull request has been automatically closed because there has
    been no activity for 90 days. Please feel free to reopen this pull
    request (or open a new one) if the proposed change is still
    appropriate. Thank you for your contribution!

issues:
  # Comment to post when marking as stale. Set to `false` to disable
  markComment: >
    This issue has been automatically marked as stale because it
    has not had any activity for 60 days. It will be closed if no further
    activity occurs for another 30 days.

  # Comment to post when removing the stale label.
  unmarkComment: >
    Thank you for updating this issue. It is no longer marked as stale.

  # Comment to post when closing a stale Issue.
  closeComment: >
    This issue has been automatically closed because there has
    been no activity for 90 days. We are sorry that we haven't been
    able to prioritize it yet. Please feel free to reopen this
    issue or create a new one. Thank you!

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30

# Limit to only `issues` or `pulls`
# only: pulls

# Optionally, specify configuration settings that are specific to just 'issues' or 'pulls':
# pulls:
#   daysUntilStale: 30
#   markComment: >
#     This pull request has been automatically marked as stale because it has not had
#     recent activity. It will be closed if no further activity occurs. Thank you
#     for your contributions.

# issues:
#   exemptLabels:
#     - confirmed
