#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://www.cyberciti.biz/faq/disable-the-mail-alert-by-crontab-command
# http://www.cyberciti.biz/faq/how-do-i-add-jobs-to-cron-under-linux-or-unix-oses
# http://wiki.dreamhost.com/index.php/Crontab

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_CRONTAB_POWERMNGMT_CONFIG=${OMV_CRONTAB_POWERMNGMT_CONFIG:-"/etc/cron.d/openmediavault-powermngmt"}

# Create the power management cron jobs.
xmlstarlet sel -t \
  -o "SHELL=/bin/sh" -n \
  -o "PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin" -n \
  -o "# m h dom mon dow user    command" -n \
  -m "//system/crontab/job[type='reboot' or type='shutdown' or type='standby'][enable='1']" \
    -i "execution[. = 'exactly']" \
  	  -i "everynminute[. = '1']" -v "concat('*/',minute,' ')" -b \
	  -i "everynminute[. = '0']" -v "concat(minute,' ')" -b \
	  -i "everynhour[. = '1']" -v "concat('*/',hour,' ')" -b \
	  -i "everynhour[. = '0']" -v "concat(hour,' ')" -b \
	  -i "everyndayofmonth[. = '1']" -v "concat('*/',dayofmonth,' ')" -b \
	  -i "everyndayofmonth[. = '0']" -v "concat(dayofmonth,' ')" -b \
	  -v "concat(month,' ',dayofweek)" \
    -b \
    -i "execution[. != 'exactly']" \
      -v "concat('@',execution)" \
    -b \
    -v "concat(' ',username,' ',command,' >/dev/null 2>&1')" -n \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_CRONTAB_POWERMNGMT_CONFIG}
chmod 644 ${OMV_CRONTAB_POWERMNGMT_CONFIG}
