#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2014 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

_omv-mkconf()
{
	local cur

	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"

	OMV_MKCONF_SCRIPTS_DIR="/usr/share/openmediavault/mkconf"

	COMPREPLY=( $( compgen -W '$( command find ${OMV_MKCONF_SCRIPTS_DIR} \
	  -maxdepth 1 -type f -printf "%f\n" 2>/dev/null )' -- "$cur"  ) )
}
complete -F _omv-mkconf omv-mkconf
