#!/usr/bin/env dash
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2025 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

enabled=$(systemctl is-enabled onedrive@onedrive.service)
username=$(omv-confdbadm read 'conf.service.onedrive' | jq --raw-output '.username')

stop_onedrive_service() {
  if [ ${enabled} ]; then
    echo "Please wait, stopping service ..."
    systemctl stop onedrive@onedrive.service || true
  fi
}

start_onedrive_service() {
  if [ ${enabled} ]; then
    echo "Please wait, starting service ..."
    systemctl start onedrive@onedrive.service || true
  fi
}

stop_onedrive_service
trap start_onedrive_service 2
sudo -u "${username}" onedrive --confdir /var/cache/onedrive/ --reauth
if [ $? -eq 126 ]; then
  sudo -u "${username}" onedrive --confdir /var/cache/onedrive/ --resync
fi
trap - 2
start_onedrive_service

exit 0
