#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2014 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

. /lib/partman/lib/base.sh

if [ $(list-devices disk | wc -l) -gt 1 ]; then
	logger -t partman "More than one target storage device detected"
	db_capb
	db_input critical openmediavault-installer/partman/multiple_target_devices || true
	db_go || true
	db_capb backup
	db_set debian-installer/exit/always_halt false
	db_set debian-installer/exit/halt false
	db_set debian-installer/exit/poweroff true
	/lib/debian-installer/exit
fi

exit 0
