#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2014 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# http://ticktoo.com/blog/32-Linux+Software+Raid%3A+mdadm+Performance+Tuning
# http://www.cyberciti.biz/tips/linux-raid-increase-resync-rebuild-speed.html

set -e

. /etc/default/openmediavault

OMV_SYSCTL_MDADM_CONFIG=${OMV_SYSCTL_MDADM_CONFIG:-"/etc/sysctl.d/99-openmediavault-mdadm.conf"}
OMV_SYSCTL_DEV_RAID_SPEEDLIMITMIN=${OMV_SYSCTL_DEV_RAID_SPEEDLIMITMIN:-"10000"}

# Improve maximun md array reconstruction speed
cat <<EOF > ${OMV_SYSCTL_MDADM_CONFIG}
dev.raid.speed_limit_min=${OMV_SYSCTL_DEV_RAID_SPEEDLIMITMIN}
EOF
