version: "1.0"
type: component
data:
  name: omv-services-k8s-resources-configmap-datatable-page
  type: datatablePage
  config:
    autoReload: 10000
    stateId: 30a46982-d7a9-11ee-8289-af002211935a
    sorters:
      - dir: asc
        prop: metadata.namespace
      - dir: asc
        prop: metadata.name
    store:
      proxy:
        service: Kubectl
        get:
          method: getList
          params:
            type: configmaps
    rowId: metadata.name
    rowEnumFmt: "{{ metadata.namespace }}/{{ metadata.name }}"
    selectionType: single
    hasSearchField: true
    columns:
      - name: _("Namespace")
        prop: metadata.namespace
        flexGrow: 1
        sortable: true
      - name: _("Name")
        prop: metadata.name
        flexGrow: 1
        sortable: true
      - name: _("Data")
        prop: data
        flexGrow: 1
        sortable: false
        cellTemplateName: template
        cellTemplateConfig: "{{ data | length }}"
      - name: _("Created")
        prop: metadata.creationTimestamp
        flexGrow: 1
        sortable: true
        cellTemplateName: relativeTime
    actions:
      - type: iconButton
        icon: show
        tooltip: _("View")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: url
          url: "/services/k8s/resources/configmap/get/{{ _selected[0].metadata.name }}?namespace={{ _selected[0].metadata.namespace }}&type=configmap"
      - type: iconButton
        icon: "mdi:text-box-edit"
        tooltip: _("Describe")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: url
          url: "/services/k8s/resources/configmap/describe/{{ _selected[0].metadata.name }}?namespace={{ _selected[0].metadata.namespace }}&type=configmap"
      - template: delete
        execute:
          type: request
          request:
            service: Kubectl
            method: delete
            params:
              type: configmap
              name: "{{ metadata.name }}"
              namespace: "{{ metadata.namespace }}"
