version: "1.0"
type: component
data:
  name: omv-services-k8s-resources-ingressroute-datatable-page
  type: datatablePage
  config:
    autoReload: 10000
    stateId: b04a0aea-d6df-11ee-ab90-27c48cdce0b0
    sorters:
      - dir: asc
        prop: metadata.namespace
      - dir: asc
        prop: metadata.name
    store:
      proxy:
        service: Kubectl
        get:
          method: getList
          params:
            type: ingressroutes
    rowId: metadata.name
    rowEnumFmt: "{{ metadata.namespace }}/{{ metadata.name }}"
    selectionType: single
    hasSearchField: true
    columns:
      - name: _("Namespace")
        prop: metadata.namespace
        flexGrow: 1
        sortable: true
      - name: _("Name")
        prop: metadata.name
        flexGrow: 1
        sortable: true
      - name: _("Created")
        prop: metadata.creationTimestamp
        flexGrow: 1
        sortable: true
        cellTemplateName: relativeTime
    actions:
      - type: iconButton
        icon: show
        tooltip: _("View")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: url
          url: "/services/k8s/resources/ingressroute/get/{{ _selected[0].metadata.name }}?namespace={{ _selected[0].metadata.namespace }}&type=ingressroute"
      - type: iconButton
        icon: "mdi:text-box-edit"
        tooltip: _("Describe")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: url
          url: "/services/k8s/resources/ingressroute/describe/{{ _selected[0].metadata.name }}?namespace={{ _selected[0].metadata.namespace }}&type=ingressroute"
      - template: delete
        execute:
          type: request
          request:
            service: Kubectl
            method: delete
            params:
              type: ingressroute
              name: "{{ metadata.name }}"
              namespace: "{{ metadata.namespace }}"
