#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2021 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault

OMV_LOG_DIR=${OMV_LOG_DIR:-"/var/log/openmediavault"}
OMV_INITDB_FILE=${OMV_INITDB_FILE:-"/var/lib/openmediavault/initdb.req"}
OMV_INITDB_SCRIPTS_DIR=${OMV_INITDB_SCRIPTS_DIR:-"/usr/share/openmediavault/initdb"}

# Run all initialization scripts?
if test $# -gt 0; then
	# Execute the specified scripts.
	for name in $@; do
		${OMV_INITDB_SCRIPTS_DIR}/${name} 2>&1 >${OMV_LOG_DIR}/initdb.log
	done
else
	# Execute all scripts.
	run-parts --exit-on-error ${OMV_INITDB_SCRIPTS_DIR} 2>&1 >${OMV_LOG_DIR}/initdb.log
fi

# Remove the flag.
rm -f "${OMV_INITDB_FILE}"

exit 0
