#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2014 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault

OMV_INITSYSTEM_SCRIPTS_DIR=${OMV_INITSYSTEM_SCRIPTS_DIR:-"/usr/share/openmediavault/initsystem"}

# Run all system initialization scripts.
if test $# -gt 0; then
	# Execute only given scripts.
	for name in $@; do
		${OMV_INITSYSTEM_SCRIPTS_DIR}/${name} 2>&1 >${OMV_LOG_DIR}/initsystem.log
	done
else
	# Execute all scripts.
	run-parts --report ${OMV_INITSYSTEM_SCRIPTS_DIR} 2>&1 >${OMV_LOG_DIR}/initsystem.log
fi

# Remove the flag.
rm -f ${OMV_INITSYSTEM_FILE}

exit 0
