#!/usr/bin/env python3
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.
import argparse
import sys
import json
import openmediavault.log


def main():
    parser = argparse.ArgumentParser(
        description="Convert JSON data to "
        "human-readable form."
    )
    parser.add_argument(
        "file",
        help="The JSON file to prettify. If not "
        "defined, stdin will be used.",
        nargs="?"
    )
    args = parser.parse_args()
    try:
        inFile = sys.stdin
        if args.file is not None:
            inFile = open(args.file)
        data = json.load(inFile)
        inFile.close()
    except Exception as e:
        openmediavault.log.error(str(e))
        return 1
    print(json.dumps(data, sort_keys=False, indent=4))
    return 0


if __name__ == "__main__":
    sys.exit(main())
