#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2012 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://linux-raid.osdl.org/index.php/RAID_setup
# http://wiki.linuxquestions.org/wiki/Fstab

set -e

devices=$(mdadm --detail --brief --verbose $1 | tail -n 1 | sed 's/.*devices=\(.*\)/\1/')

mdadm --manage --stop $1 2>&1
IFS=","
for device in ${devices}
do
	mdadm --zero-superblock --force ${device} 2>&1
done

exit 0
