#!/usr/bin/env python3
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2022 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

import glob
import json
import os

import openmediavault.log
import polib

i18n_dir = openmediavault.getenv(
    'OMV_I18N_LOCALE_DIR', '/usr/share/openmediavault/locale')
wb_i18n_dir = openmediavault.getenv(
    'OMV_WORKBENCH_I18N_ASSETS_DIR', '/var/www/openmediavault/assets/i18n')

for i18n_dir_path in glob.iglob(os.path.join(i18n_dir, '*')):
    if not os.path.isdir(i18n_dir_path):
        continue

    lang = os.path.basename(i18n_dir_path)
    asset_path = os.path.join(wb_i18n_dir, lang)
    translations = {}

    for i18n_po_file in glob.iglob(os.path.join(i18n_dir_path, '*.po')):
        po = polib.pofile(i18n_po_file)
        for entry in po.translated_entries():
            if entry.msgid and entry.msgstr:
                translations[entry.msgid] = entry.msgstr

    with open(asset_path, 'w') as fd:
        fd.write(json.dumps(translations, indent=2))
    openmediavault.log.info('Successfully created "%s".', asset_path)
