#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2014 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

usage() {
	cat <<EOF
Usage:
  $(basename $0) [options]

Create the indexes of upgradeable packages and ${prdname} plugins.

OPTIONS:
  -h  Show this message.

EOF
}

cleanup() {
	rm -f ${pidfile}
	exit
}

pidfile="/var/run/$(basename $0).pid"
prdname=$(omv_product_info "name")

# Process the command line arguments.
while getopts "?h" option
do
	case ${option} in
	h|?)
		usage >&2
		exit 0
		;;
	esac
done

# Check if another instance is already running.
if [ -e ${pidfile} ]; then
	echo "Another instance is already running" >/dev/stderr
	exit 1
fi

# Automatically cleanup PID file.
trap cleanup 0 1 2 5 15
echo $$ > ${pidfile}

echo "Creating index of upgradeable packages ..."
omv_exec_rpc "Apt" "createIndex" "{}"
[ $? -ne 0 ] && exit 1

echo "Creating index of ${prdname} plugins ..."
omv_exec_rpc "Plugin" "createIndex" "{}"
[ $? -ne 0 ] && exit 1

exit 0
