#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2014 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /usr/share/openmediavault/sysinfo/functions

name=$(omv_product_info "name")
packagename=$(omv_product_info "packagename")
versionname=$(omv_product_info "versionname")
version=$(dpkg-query -W -f='${Version}' ${packagename})

omv_sysinfo_begin_msg "${name} information"
omv_sysinfo_msg "Release: ${version}"
omv_sysinfo_msg "Codename: ${versionname}"
omv_sysinfo_end_msg

exit 0
