#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2015 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /usr/share/openmediavault/sysinfo/functions

omv_sysinfo_begin_msg "Network interfaces"
ip addr show | omv_sysinfo_msg
for devicefile in $(find /sys/class/net -maxdepth 1 -not -iname "lo" -type l -printf "%f\n") ; do
	omv_sysinfo_msg_separator
	omv_sysinfo_msg_caption "Interface information ${devicefile}"
	ethtool ${devicefile}
	omv_sysinfo_msg_separator
	omv_sysinfo_msg_caption "Driver information ${devicefile}"
	ethtool -i ${devicefile} || : | omv_sysinfo_msg
done
omv_sysinfo_end_msg

exit 0
