version: "1.0"
type: component
data:
  name: omv-services-ftp-settings-form-page
  type: formPage
  config:
    request:
      service: FTP
      get:
        method: getSettings
      post:
        method: setSettings
    fields:
      - type: checkbox
        name: enable
        label: _("Enabled")
        value: false
      - type: numberInput
        name: port
        label: _("Port")
        value: 21
        validators:
          required: true
          min: 1
          max: 65535
          patternType: port
      - type: numberInput
        name: maxclients
        label: _("Max. clients")
        hint: _("Maximum number of simultaneous clients.")
        value: 5
        validators:
          required: true
          min: 0
          patternType: integer
      - type: numberInput
        name: maxconnectionsperhost
        label: _("Max. connections per host")
        hint: _("Maximum number of connections per IP (0 = unlimited).")
        value: 2
        validators:
          required: true
          min: 0
          patternType: integer
      - type: numberInput
        name: maxloginattempts
        label: _("Max. login attempts")
        hint: _("Maximum number of allowed password attempts before disconnection.")
        value: 1
        validators:
          required: true
          min: 0
          patternType: integer
      - type: numberInput
        name: timeoutidle
        label: _("Timeout")
        hint: _("Maximum idle time in seconds. Setting idle timeout to 0 disables the idle timer completely (clients can stay connected for ever, without sending data).")
        value: 1200
        validators:
          required: true
          min: 0
          patternType: integer
      - type: checkbox
        name: anonymous
        label: _("Anonymous FTP")
        value: false
      - type: textarea
        name: displaylogin
        label: _("Welcome message")
        value: ''
        hint: _("The welcome message will be displayed to the user at login. Please check the <a href='http://www.proftpd.org/docs/howto/DisplayFiles.html' target='_blank'>manual page</a> how to use variables. Leave this field empty to disable the welcome message.")
      - type: divider
        title: _("Home directories")
      - type: checkbox
        name: homesenable
        label: _("Enabled")
        hint: _("Display the home directory of the user in the browse list.")
        value: false
      - type: divider
        title: _("Advanced settings")
      - type: checkbox
        name: rootlogin
        label: _("Permit root login")
        hint: _("Specifies whether it is allowed to login as superuser directly.")
        value: false
      - type: checkbox
        name: requirevalidshell
        label: _("Require valid shell")
        hint: _("Deny logins which do not have a valid shell.")
        value: true
      - type: checkbox
        name: limittransferrate
        label: _("Bandwidth restriction")
        hint: _("Use the following bandwidth restriction.")
        value: false
      - type: container
        fields:
          - type: numberInput
            name: maxuptransferrate
            label: _("Maximum upload rate (KiB/s)")
            hint: _("0 KiB/s means unlimited.")
            value: 0
            modifiers:
              - type: disabled
                constraint:
                  operator: falsy
                  arg0:
                    prop: limittransferrate
            validators:
              min: 0
              patternType: integer
              required: true
          - type: numberInput
            name: maxdowntransferrate
            label: _("Maximum download rate (KiB/s)")
            hint: _("0 KiB/s means unlimited.")
            value: 0
            modifiers:
              - type: disabled
                constraint:
                  operator: falsy
                  arg0:
                    prop: limittransferrate
            validators:
              min: 0
              patternType: integer
              required: true
      - type: checkbox
        name: usepassiveports
        label: _("Passive FTP")
        hint: _("In some cases you have to specify passive ports range to by-pass firewall limitations. Passive ports restricts the range of ports from which the server will select when sent the PASV command from a client. The server will randomly choose a number from within the specified range until an open port is found. The port range selected must be in the non-privileged range (eg. greater than or equal to 1024). It is strongly recommended that the chosen range be large enough to handle many simultaneous passive connections (for example, 49152-65534, the IANA-registered ephemeral port range).")
        value: false
      - type: container
        fields:
          - type: numberInput
            name: minpassiveports
            label: _("Min. passive port")
            value: 49152
            modifiers:
              - type: disabled
                constraint:
                  operator: falsy
                  arg0:
                    prop: usepassiveports
            validators:
              patternType: port
              min: 1025
              max: 65535
              required: true
          - type: numberInput
            name: maxpassiveports
            label: _("Max. passive port")
            value: 65534
            modifiers:
              - type: disabled
                constraint:
                  operator: falsy
                  arg0:
                    prop: usepassiveports
            validators:
              patternType: port
              min: 1025
              max: 65535
              required: true
      - type: container
        fields:
          - type: textInput
            name: masqueradeaddress
            label: _("Masquerade address")
            value: ''
            hint: _("If your host is acting as a NAT gateway or port forwarder for the server, this option is useful in order to allow passive tranfers to work. You have to use your public address and opening the passive ports used on your firewall as well.")
            validators:
              patternType: domainNameIp
          - type: numberInput
            label: _("Refresh time")
            name: dynmasqrefresh
            hint: _("Specifies the amount of time, in seconds, between checking and updating the masquerade address by resolving the IP address. Set this value to 0 to disable this option.")
            value: 0
            modifiers:
              - type: disabled
                constraint:
                  operator: z
                  arg0:
                    prop: masqueradeaddress
            validators:
              min: 0
              patternType: integer
              required: true
      - type: checkbox
        name: allowforeignaddress
        label: _("FXP")
        hint: _("FXP allows transfers between two remote servers without any file data going to the client asking for the transfer.")
        value: false
      - type: checkbox
        name: allowrestart
        label: _("Resume")
        hint: _("Allow clients to resume interrupted uploads and downloads.")
        value: false
      - type: checkbox
        name: identlookups
        label: _("Ident protocol")
        hint: _("When a client initially connects to the server the ident protocol is used to attempt to identify the remote user name.")
        value: false
      - type: checkbox
        name: usereversedns
        label: _("Reverse DNS lookup")
        hint: _("Enable reverse DNS lookup performed on the remote host's IP address for incoming active mode data connections and outgoing passive mode data connections.")
        value: false
      - type: checkbox
        name: transferlog
        label: _("Transfer log")
        hint: _("Enable file transfer logging.")
        value: false
      - type: textarea
        name: extraoptions
        label: _("Extra options")
        hint: _("Please check the <a href='http://www.proftpd.org/docs/directives/configuration_full.html' target='_blank'>manual page</a> for more details.")
        value: ''
    buttons:
      - template: submit
      - template: cancel
        execute:
          type: url
          url: /services/ftp
