#!/usr/bin/env dash
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2023 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

MAILTO=""
OMV_BTRFS_SCRUB_ENABLED=${OMV_BTRFS_SCRUB_ENABLED:-"yes"}
OMV_BTRFS_SCRUB_PRIORITY=${OMV_BTRFS_SCRUB_PRIORITY:-"-c 2 -n 4"}
OMV_BTRFS_SCRUB_READONLY=${OMV_BTRFS_SCRUB_READONLY:-"no"}

# Exit immediately if Btrfs scrubbing is disabled.
! omv_checkyesno "${OMV_BTRFS_SCRUB_ENABLED}" && exit 0

omv_log "Performing a scrub on Btrfs file systems."
# Ignore subvolumes.
findmnt --all --canonicalize --notruncate --nofsroot --uniq --noheadings --output SOURCE,UUID --types btrfs |
  sort | uniq |
  while read device uuid
do
  omv_log "Scrubbing the file system on ${device} [UUID=${uuid}] ..."

  cmdargs="${OMV_BTRFS_SCRUB_PRIORITY}"
  if omv_checkyesno ${OMV_BTRFS_SCRUB_READONLY}; then
    cmdargs="${cmdargs} -r"
  fi

  stats=$(btrfs scrub start -B -d ${cmdargs} "${device}")
  # Ignore the file system notification settings because of the
  # importance of this message.
  (
    echo "Scrubbing the Btrfs file system on ${device} [UUID=${uuid}] has been finished.";
    echo "${stats}"
  ) | mail -E -s "Scrub report of the file system ${device} [UUID=${uuid}]" root
done
