# -*- mode: ruby -*-
#
# This file is part of openmediavault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2016 Volker Theile
#
# openmediavault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# openmediavault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openmediavault. If not, see <http://www.gnu.org/licenses/>.

Vagrant.configure("2") do |config|
	config.vm.box = "debian/jessie64"
	config.vm.network "private_network", ip: "192.172.16.22"
	config.vm.hostname = "omv3-box"
	config.vm.provider :virtualbox do |prov|
		prov.name = "omv3-box"
		prov.memory = "2048"
	end
	config.vm.provider :libvirt do |prov|
		prov.memory = "2048"
	end
	config.vm.provision :shell, :path => "bootstrap.sh"
end
