/**
 * This file is part of OpenMediaVault.
 *
 * @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
 * @author    Volker Theile <volker.theile@openmediavault.org>
 * @copyright Copyright (c) 2009-2025 Volker Theile
 *
 * OpenMediaVault is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * OpenMediaVault is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
// eslint-disable-next-line no-shadow
export enum Icon {
  user = 'mdi:account',
  users = 'mdi:account-multiple',
  group = 'mdi:account-group',
  password = 'mdi:lock',
  home = 'mdi:home',
  save = 'mdi:content-save',
  add = 'mdi:plus-circle',
  remove = 'mdi:minus-circle',
  edit = 'mdi:pencil',
  delete = 'mdi:delete',
  copy = 'mdi:content-copy',
  cancel = 'mdi:cancel',
  clear = 'mdi:close',
  show = 'mdi:eye',
  undo = 'mdi:undo',
  reload = 'mdi:reload',
  reset = 'mdi:refresh',
  import = 'mdi:import',
  check = 'mdi:check',
  checkBoxMarked = 'mdi:checkbox-marked-outline',
  checkBoxBlank = 'mdi:checkbox-blank-outline',
  plus = 'mdi:plus',
  minus = 'mdi:minus',
  start = 'mdi:play',
  stop = 'mdi:stop',
  pause = 'mdi:pause',
  skipNext = 'mdi:skip-next',
  skipPrevious = 'mdi:skip-previous',
  eject = 'mdi:eject',
  success = 'mdi:check',
  error = 'mdi:close-circle',
  information = 'mdi:information-outline',
  warning = 'mdi:alert',
  help = 'mdi:help',
  question = 'mdi:help-circle',
  harddisk = 'mdi:harddisk',
  arrowLeft = 'mdi:arrow-left',
  arrowRight = 'mdi:arrow-right',
  arrowUp = 'mdi:arrow-up',
  arrowDown = 'mdi:arrow-down',
  chevronLeft = 'mdi:chevron-left',
  chevronRight = 'mdi:chevron-right',
  chevronUp = 'mdi:chevron-up',
  chevronDown = 'mdi:chevron-down',
  power = 'mdi:power',
  logout = 'mdi:logout-variant',
  reboot = 'mdi:repeat',
  standby = 'mdi:pause',
  shutdown = 'mdi:power',
  navicon = 'mdi:navicon',
  cogs = 'mdi:cogs',
  settings = 'mdi:cog',
  clock = 'mdi:clock-outline',
  network = 'mdi:lan',
  email = 'mdi:email',
  menu = 'mdi:menu',
  dotmenu = 'mdi:dots-vertical',
  bell = 'mdi:bell',
  apps = 'mdi:apps',
  laptop = 'mdi:laptop',
  server = 'mdi:server',
  nas = 'mdi:nas',
  key = 'mdi:key',
  share = 'mdi:share-variant',
  heartPulse = 'mdi:heart-pulse',
  tune = 'mdi:tune',
  ssl = 'mdi:lock',
  ssh = 'mdi:ssh',
  ftp = 'mdi:server-network',
  smb = 'mdi:microsoft-windows',
  nfs = 'mdi:folder-network',
  plugin = 'mdi:puzzle',
  search = 'mdi:magnify',
  eraser = 'mdi:eraser',
  table = 'mdi:table',
  tip = 'mdi:lightbulb-on-outline',
  details = 'mdi:details',
  expand = 'mdi:arrow-expand',
  collapse = 'mdi:arrow-collapse',
  folder = 'mdi:folder',
  console = 'mdi:console',
  close = 'mdi:window-close',
  restore = 'mdi:restore',
  link = 'mdi:link-variant',
  download = 'mdi:download',
  docs = 'mdi:file-document'
}
