#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_APT_USE_KERNEL_BACKPORTS=${OMV_APT_USE_KERNEL_BACKPORTS:-"yes"}
OMV_APT_KERNEL_BACKPORTS_ARCHIVE=${OMV_APT_KERNEL_BACKPORTS_ARCHIVE:-"$(lsb_release --short --codename)-backports"}
OMV_APT_KERNEL_BACKPORTS_PINPRIORITY=${OMV_APT_KERNEL_BACKPORTS_PINPRIORITY:-"500"}

# Remove existing configuration files.
rm -f /etc/apt/preferences.d/openmediavault-kernel-backports.pref
rm -f /etc/apt/sources.list.d/openmediavault-kernel-backports.list

! omv_checkyesno "${OMV_APT_USE_KERNEL_BACKPORTS}" && exit 0;

# Create the configuration files.
cat <<EOF > /etc/apt/preferences.d/openmediavault-kernel-backports.pref
Package: linux-base
Pin: release a=${OMV_APT_KERNEL_BACKPORTS_ARCHIVE}
Pin-Priority: ${OMV_APT_KERNEL_BACKPORTS_PINPRIORITY}

Package: linux-headers-*
Pin: release a=${OMV_APT_KERNEL_BACKPORTS_ARCHIVE}
Pin-Priority: ${OMV_APT_KERNEL_BACKPORTS_PINPRIORITY}

Package: linux-image-*
Pin: release a=${OMV_APT_KERNEL_BACKPORTS_ARCHIVE}
Pin-Priority: ${OMV_APT_KERNEL_BACKPORTS_PINPRIORITY}

Package: firmware-*
Pin: release a=${OMV_APT_KERNEL_BACKPORTS_ARCHIVE}
Pin-Priority: ${OMV_APT_KERNEL_BACKPORTS_PINPRIORITY}
EOF

cat <<EOF > /etc/apt/sources.list.d/openmediavault-kernel-backports.list
deb http://httpredir.debian.org/debian ${OMV_APT_KERNEL_BACKPORTS_ARCHIVE} main contrib non-free
EOF
