#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# https://wiki.ubuntuusers.de/Proxyserver

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_APT_PROXY_CONFIG=${OMV_APT_PROXY_CONFIG:-"/etc/apt/apt.conf.d/99openmediavault-proxy"}
OMV_APT_PROXY_CONFIG_MASK=${OMV_APT_PROXY_CONFIG_MASK:-"640"}

xmlstarlet sel -t \
  -m "//system/network/proxy/http" \
    -i "enable = '1' and string-length(host) > 0" \
      -o "Acquire::http::Proxy \"http://" \
      -i "string-length(username) > 0" \
        -v "concat(username,':',password,'@')" \
      -b \
      -v "concat(host,':',port,'\";')" -n \
    -b \
  -b \
  -m "//system/network/proxy/https" \
    -i "enable = '1' and string-length(host) > 0" \
      -o "Acquire::https::Proxy \"https://" \
      -i "string-length(username) > 0" \
        -v "concat(username,':',password,'@')" \
      -b \
      -v "concat(host,':',port,'\";')" -n \
    -b \
  -b \
  -m "//system/network/proxy/ftp" \
    -i "enable = '1' and string-length(host) > 0" \
      -o "Acquire::ftp::Proxy \"ftp://" \
      -i "string-length(username) > 0" \
        -v "concat(username,':',password,'@')" \
      -b \
      -v "concat(host,':',port,'\";')" -n \
    -b \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_APT_PROXY_CONFIG}
chmod ${OMV_APT_PROXY_CONFIG_MASK} ${OMV_APT_PROXY_CONFIG}
