#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2022 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

# Make sure the command does not do anything during the distribution upgrade.
dpkg-divert --rename --divert /usr/sbin/omv-mkaptidx.real /usr/sbin/omv-mkaptidx
touch /usr/sbin/omv-mkaptidx
chmod 755 /usr/sbin/omv-mkaptidx
cat > /usr/sbin/omv-mkaptidx <<EOF
#!/bin/sh
exit 0
EOF

exit 0
