#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2022 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

# The tally2 PAM module has been replaced by faillock.
# To prevent errors during the distribution upgrade we need to ensure
# the files are empty. Additionally we need to ensure that the new
# files shipped by the 'openmediavault' package are installed properly.
for filename in "openmediavault" "openmediavault-common-auth" "openmediavault-webgui"; do
  dpkg-divert --rename --divert "/etc/pam.d/${filename}.real" "/etc/pam.d/${filename}"
  echo > "/etc/pam.d/${filename}"
done

exit 0
