#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_PROFTPD_CONFIG=${OMV_PROFTPD_CONFIG:-"/etc/proftpd/proftpd.conf"}
OMV_PROFTPD_MODWRAP_TCPACCESSFILES=${OMV_PROFTPD_MODWRAP_TCPACCESSFILES:-"/etc/hosts.allow /etc/hosts.deny"}
OMV_PROFTPD_MODWRAP_TCPACCESSSYSLOGLEVELS=${OMV_PROFTPD_MODWRAP_TCPACCESSSYSLOGLEVELS:-"info warn"}
OMV_PROFTPD_MODWRAP_TCPSERVICENAME=${OMV_PROFTPD_MODWRAP_TCPSERVICENAME:-"ftpd"}

for hostsfile in ${OMV_PROFTPD_MODWRAP_TCPACCESSFILES}
do
	if [ ! -f "${hostsfile}" ]; then
		touch "${hostsfile}"
		chmod 644 "${hostsfile}"
	fi
done

	cat >> ${OMV_PROFTPD_CONFIG} <<EOF
<IfModule mod_wrap.c>
  TCPAccessFiles ${OMV_PROFTPD_MODWRAP_TCPACCESSFILES}
  TCPAccessSyslogLevels ${OMV_PROFTPD_MODWRAP_TCPACCESSSYSLOGLEVELS}
  TCPServiceName ${OMV_PROFTPD_MODWRAP_TCPSERVICENAME}
</ifModule>
EOF
