#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2016 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e


if [ -e "/etc/udev/udev.conf" ]; then
	. /etc/udev/udev.conf
	if [ "${udev_log}" = "debug" ]; then
		set -x
	fi
fi

RULES_FILE="/etc/udev/rules.d/61-openmediavault-dev-root-link.rules"

. /lib/udev/rule_generator.functions

# Link the temporary rules file to /run/udev/rules.d to be triggered
# by the systemd-udev-trigger.service systemd unit.
# Note, temporary rules files are copied to the r/w file system by the
# udev-finish.service systemd unit which is executed after the
# systemd-udev-trigger.service unit. Because of that, such temporary
# rules are not triggered during the boot process. To ensure that the
# rule is trigger during bootup, create a link to /run/udev/rules.d.
ln_rules_file() {
	RUNDIR="/run/udev"
    [ -e "$RUNDIR" ] || return 0

	local tmp_rules_file="${RUNDIR}/rules.d/${RO_RULES_FILE##*/}"
	mkdir -p "${RUNDIR}/rules.d"
	ln -s "${RULES_FILE}" "${tmp_rules_file}"
}

[ -e "${RULES_FILE}" ] && exit 0

eval $(udevadm info --export --export-prefix=ROOT_ --device-id-of-file=/ || true)
[ "${ROOT_MAJOR}" -a "${ROOT_MINOR}" ] || exit 0
[ "${ROOT_MAJOR}" != 0 ] || exit 0

lock_rules_file
choose_rules_file
echo 'ACTION=="add|change", SUBSYSTEM=="block", ENV{MAJOR}=="'${ROOT_MAJOR}'", ENV{MINOR}=="'${ROOT_MINOR}'", SYMLINK+="root"' > ${RULES_FILE}
ln_rules_file
unlock_rules_file

exit 0
