#!/usr/bin/env dash
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2025 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.
#
# Testing:
# anacron -f -n
MAILTO=""

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_BTRFS_SCRUB_ENABLED=${OMV_BTRFS_SCRUB_ENABLED:-"yes"}
OMV_BTRFS_SCRUB_PERIOD=${OMV_BTRFS_SCRUB_PERIOD:-"monthly"}

# Exit immediately if Btrfs scrubbing is disabled.
! omv_checkyesno "${OMV_BTRFS_SCRUB_ENABLED}" && exit 0

# Exit immediately if Btrfs scrubbing period is not 'monthly'.
[ "${OMV_BTRFS_SCRUB_PERIOD}" != "monthly" ] && exit 0

omv-btrfs-scrub -e >/dev/null 2>&1
