#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2019 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://wiki.nginx.org/Pitfalls#Taxing_Rewrites
# http://security.stackexchange.com/questions/54639/nginx-recommended-ssl-ciphers-for-security-compatibility-with-pfs
# http://en.wikipedia.org/wiki/List_of_HTTP_header_fields
# http://www.pedaldrivenprogramming.com/2015/04/upgrading-wheezy-to-jessie:-nginx-and-php-fpm/
# https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=nginx-1.10.3&openssl=1.1.0f&hsts=yes&profile=modern

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_SSL_CERTIFICATE_DIR=${OMV_SSL_CERTIFICATE_DIR:-"/etc/ssl"}
OMV_SSL_CERTIFICATE_PREFIX=${OMV_SSL_CERTIFICATE_PREFIX:-"openmediavault-"}

OMV_NGINX_SITE_WEBGUI_LOG_DIR=${OMV_NGINX_SITE_WEBGUI_LOG_DIR:-"/var/log/nginx"}
OMV_NGINX_SITE_WEBGUI_SERVERNAME=${OMV_NGINX_SITE_WEBGUI_SERVERNAME:-"openmediavault-webgui"}
OMV_NGINX_SITE_WEBGUI_CONFIG=${OMV_NGINX_SITE_WEBGUI_CONFIG:-"/etc/nginx/sites-available/openmediavault-webgui"}
OMV_NGINX_SITE_WEBGUI_INCLUDE_DIR=${OMV_NGINX_SITE_WEBGUI_INCLUDE_DIR:-"/etc/nginx/openmediavault-webgui.d"}
OMV_NGINX_SITE_WEBGUI_LOGLEVEL=${OMV_NGINX_SITE_WEBGUI_LOGLEVEL:-"error"}
OMV_NGINX_SITE_WEBGUI_CLIENT_MAX_BODY_SIZE=${OMV_NGINX_SITE_WEBGUI_CLIENT_MAX_BODY_SIZE:-"25M"}
OMV_NGINX_SITE_WEBGUI_CONTENT_EXPIRES=${OMV_NGINX_SITE_WEBGUI_CONTENT_EXPIRES:-"2d"}
OMV_NGINX_SITE_WEBGUI_SECURITY_CONFIG=${OMV_NGINX_SITE_WEBGUI_SECURITY_CONFIG:-"${OMV_NGINX_SITE_WEBGUI_INCLUDE_DIR}/security.conf"}
OMV_NGINX_SITE_WEBGUI_SECURITY_CSP_ENABLE=${OMV_NGINX_SITE_WEBGUI_SECURITY_CSP_ENABLE:-"yes"}
OMV_NGINX_SITE_WEBGUI_SECURITY_CSP=${OMV_NGINX_SITE_WEBGUI_SECURITY_CSP:-"default-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data:;"}
OMV_NGINX_SITE_WEBGUI_SECURITY_XFRAMEOPTIONS_ENABLE=${OMV_NGINX_SITE_WEBGUI_SECURITY_XFRAMEOPTIONS_ENABLE:-"yes"}
OMV_NGINX_SITE_WEBGUI_SECURITY_XFRAMEOPTIONS=${OMV_NGINX_SITE_WEBGUI_SECURITY_XFRAMEOPTIONS:-"SAMEORIGIN"}
OMV_NGINX_SITE_WEBGUI_SECURITY_HSTS=${OMV_NGINX_SITE_WEBGUI_SECURITY_HSTS:-"max-age=15768000; includeSubdomains"}
OMV_NGINX_SITE_WEBGUI_FASTCGI_READ_TIMEOUT=${OMV_NGINX_SITE_WEBGUI_FASTCGI_READ_TIMEOUT:-"60s"}
OMV_NGINX_SITE_WEBGUI_FASTCGI_PARAM_SCRIPT_FILENAME=${OMV_NGINX_SITE_WEBGUI_FASTCGI_PARAM_SCRIPT_FILENAME:-"\$document_root\$fastcgi_script_name"}
OMV_NGINX_SITE_WEBGUI_SSL_PROTOCOLS=${OMV_NGINX_SITE_WEBGUI_SSL_PROTOCOLS:-"TLSv1.2"}
OMV_NGINX_SITE_WEBGUI_SSL_PREFER_SERVER_CIPHERS=${OMV_NGINX_SITE_WEBGUI_SSL_PREFER_SERVER_CIPHERS:-"on"}
OMV_NGINX_SITE_WEBGUI_SSL_CIPHERS=${OMV_NGINX_SITE_WEBGUI_SSL_CIPHERS:-"ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256"}

# Check if IPv6 is enabled. Set enabled by default.
ipv6enabled=1
if ! omv_is_ipv6_enabled; then
	ipv6enabled=0
fi

# Disable adding or modifying the “Expires” and “Cache-Control” response
# header fields if debugging is enabled.
if omv_checkyesno "${OMV_DEBUG_EXTJS}"; then
	OMV_NGINX_SITE_WEBGUI_CONTENT_EXPIRES="off"
fi

# Create '/etc/nginx/sites-available/openmediavault-webgui' file
xmlstarlet sel -t -m "//webadmin" \
  -o "server {" -n \
  -o "    server_name ${OMV_NGINX_SITE_WEBGUI_SERVERNAME};" -n \
  -o "    root ${OMV_DOCUMENTROOT_DIR};" -n \
  -o "    index index.php;" -n \
  -o "    autoindex off;" -n \
  -o "    server_tokens off;" -n \
  -o "    sendfile on;" -n \
  -o "    large_client_header_buffers 4 32k;" -n \
  -o "    client_max_body_size ${OMV_NGINX_SITE_WEBGUI_CLIENT_MAX_BODY_SIZE};" -n \
  -o "    error_log ${OMV_NGINX_SITE_WEBGUI_LOG_DIR}/${OMV_NGINX_SITE_WEBGUI_SERVERNAME}_error.log ${OMV_NGINX_SITE_WEBGUI_LOGLEVEL};" -n \
  -o "    access_log ${OMV_NGINX_SITE_WEBGUI_LOG_DIR}/${OMV_NGINX_SITE_WEBGUI_SERVERNAME}_access.log combined;" -n \
  -o "    error_page 404 = /404.php;" -n \
  -o "    location /404.html {" -n \
  -o "        internal;" -n \
  -o "    }" -n \
  -o "    location /extjs6/ {" -n \
  -o "        alias /usr/share/javascript/extjs6/;" -n \
  -o "        expires ${OMV_NGINX_SITE_WEBGUI_CONTENT_EXPIRES};" -n \
  -o "    }" -n \
  -o "    location ~ ^/(css|fonts|js|images)/ {" -n \
  -o "        expires ${OMV_NGINX_SITE_WEBGUI_CONTENT_EXPIRES};" -n \
  -o "    }" -n \
  -o "    location /favicon {" -n \
  -o "        expires 14d;" -n \
  -o "    }" -n \
  -o "    location ~ \.php$ {" -n \
  -o "        try_files \$uri =404;" -n \
  -o "        fastcgi_split_path_info ^(.+\.php)(/.+)$;" -n \
  -o "        fastcgi_pass unix:/var/run/php-fpm-openmediavault-webgui.sock;" -n \
  -o "        fastcgi_index index.php;" -n \
  -o "        fastcgi_read_timeout ${OMV_NGINX_SITE_WEBGUI_FASTCGI_READ_TIMEOUT};" -n \
  -o "        include fastcgi.conf;" -n \
  -o "        fastcgi_param SCRIPT_FILENAME ${OMV_NGINX_SITE_WEBGUI_FASTCGI_PARAM_SCRIPT_FILENAME};" -n \
  -o "    }" -n \
  -i "${ipv6enabled} = 0" \
    -v "concat('    listen ',port,';')" -n \
  -b \
  -i "${ipv6enabled} = 1" \
    -v "concat('    listen ',port,';')" -n \  
    -v "concat('    listen [::]:',port,';')" -n \
  -b \
  -i "enablessl[. = '1'] and forcesslonly[. = '1']" \
    -o "    if (\$scheme = http) {" -n \
    -o "        # Force redirection to HTTPS." -n \
    -v "concat('        return 301 https://\$host:',sslport,'\$request_uri;')" -n \
    -o "    }" -n \
  -b \
  -i "enablessl[. = '1']" \
    -i "${ipv6enabled} = 0" \
      -v "concat('    listen ',sslport,' ssl;')" -n \
    -b \
    -i "${ipv6enabled} = 1" \
      -v "concat('    listen ',sslport,' ssl;')" -n \    
      -v "concat('    listen [::]:',sslport,' ssl;')" -n \
    -b \
    -v "concat('    ssl_certificate ${OMV_SSL_CERTIFICATE_DIR}/certs/${OMV_SSL_CERTIFICATE_PREFIX}',sslcertificateref,'.crt;')" -n \
    -v "concat('    ssl_certificate_key ${OMV_SSL_CERTIFICATE_DIR}/private/${OMV_SSL_CERTIFICATE_PREFIX}',sslcertificateref,'.key;')" -n \
  -b \
  -o "    include ${OMV_NGINX_SITE_WEBGUI_INCLUDE_DIR}/*.conf;" -n \
  -o "}" \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_NGINX_SITE_WEBGUI_CONFIG}

# Create '/etc/nginx/openmediavault-webgui.d/security.conf' file
xmlstarlet sel -t -m "//webadmin" \
  -i "enablessl[. = '1']" \
    -o "# PFS (Perfect Forward Secrecy)" -n \
	-o "# https://mozilla.github.io/server-side-tls/ssl-config-generator" -n \
    -o "ssl_protocols ${OMV_NGINX_SITE_WEBGUI_SSL_PROTOCOLS};" -n \
    -o "ssl_prefer_server_ciphers ${OMV_NGINX_SITE_WEBGUI_SSL_PREFER_SERVER_CIPHERS};" -n \
    -o "ssl_ciphers '${OMV_NGINX_SITE_WEBGUI_SSL_CIPHERS}';" -n \
  -b \
  -i "enablessl[. = '1'] and forcesslonly[. = '1']" \
    -n \
    -o "# HSTS (HTTP Strict Transport Security)" -n \
    -o "# https://developer.mozilla.org/en-US/docs/Security/HTTP_Strict_Transport_Security" -n \
    -o "# https://en.wikipedia.org/wiki/SSL_stripping#SSL_stripping" -n \
    -o "add_header Strict-Transport-Security \"${OMV_NGINX_SITE_WEBGUI_SECURITY_HSTS}\";" -n \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_NGINX_SITE_WEBGUI_SECURITY_CONFIG}

if omv_checkyesno "${OMV_NGINX_SITE_WEBGUI_SECURITY_CSP_ENABLE}"; then
	cat <<EOF >> ${OMV_NGINX_SITE_WEBGUI_SECURITY_CONFIG}
# Content Security Policy (CSP)
# https://www.owasp.org/index.php/Content_Security_Policy
add_header Content-Security-Policy "${OMV_NGINX_SITE_WEBGUI_SECURITY_CSP}";

EOF
fi

if omv_checkyesno "${OMV_NGINX_SITE_WEBGUI_SECURITY_XFRAMEOPTIONS_ENABLE}"; then
	cat <<EOF >> ${OMV_NGINX_SITE_WEBGUI_SECURITY_CONFIG}
# https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options
add_header X-Frame-Options "${OMV_NGINX_SITE_WEBGUI_SECURITY_XFRAMEOPTIONS}";

EOF
fi

cat <<EOF >> ${OMV_NGINX_SITE_WEBGUI_SECURITY_CONFIG}
# http://blogs.msdn.com/b/ie/archive/2008/07/02/ie8-security-part-v-comprehensive-protection.aspx
add_header X-Content-Type-Options "nosniff";

# https://wiki.mozilla.org/Security/Features/XSS_Filter
# http://blogs.msdn.com/b/ieinternals/archive/2011/01/31/controlling-the-internet-explorer-xss-filter-with-the-x-xss-protection-http-header.aspx
add_header X-XSS-Protection "1; mode=block";
EOF
