#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2014 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_NGINX_SITE_WEBGUI_INCLUDE_DIR=${OMV_NGINX_SITE_WEBGUI_INCLUDE_DIR:-"/etc/nginx/openmediavault-webgui.d"}

OMV_NGINX_SITE_OWNCLOUD_CONFIG=${OMV_NGINX_SITE_OWNCLOUD_CONFIG:-"${OMV_NGINX_SITE_WEBGUI_INCLUDE_DIR}/owncloud.conf"}
OMV_NGINX_SITE_OWNCLOUD_DOCUMENTROOT=${OMV_NGINX_SITE_OWNCLOUD_DOCUMENTROOT:-"/var/www/owncloud"}

# !!! NOTE !!!
# The plugin uses an alias to access the ownCloud webgui because in this
# case we get SSL/TLS support out-of-the-box if the OMV webgui has enabled
# secure connection.
rm -f ${OMV_NGINX_SITE_OWNCLOUD_CONFIG}
[ "$(omv_config_get "//services/owncloud/enable")" = "0" ] && exit 0

# Create '/etc/nginx/openmediavault-webgui.d/owncloud.conf' file.
cat <<EOF > ${OMV_NGINX_SITE_OWNCLOUD_CONFIG}
location /owncloud {
	alias ${OMV_NGINX_SITE_OWNCLOUD_DOCUMENTROOT}
}
location /owncloud/~ \.php$ {
    try_files \$uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass unix:/var/run/php5-fpm-owncloud.sock;
    fastcgi_index index.php;
    include fastcgi_params;
}
EOF
