#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

# Check if one of the given OpenMediaVault plugins is installed. If it is
# installed, then suggest the deinstallation, otherwise the 1.x packages
# will break the installation.
packagename=$(omv_product_info "packagename")
pluginnames="${packagename}-nut ${packagename}-ldap ${packagename}-iscsitarget"
for pluginname in ${pluginnames}; do
	if dpkg -l | egrep "${pluginname}" >/dev/null; then
		echo "The plugin ${pluginname} has been detected."
		echo "It must be deinstalled before the installation continues. Please reinstall"
		echo "it after the system has been successfully upgraded."
		while true; do
			read -p "Do you want to deinstall this plugin [y/n]? " choice
			case "${choice}" in
			[Yy]*)
				apt-get --yes --force-yes remove "${pluginname}";
				break;;
			[Nn]*)
				echo "Aborting release upgrade"
				exit 1;;
			*)
				echo "Please answer yes or no.";;
			esac
		done
	fi
done

exit 0
