#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2015 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_AVAHIDAEMON_AFPSERVICE=${OMV_AVAHIDAEMON_AFPSERVICE:-"/etc/avahi/services/afp.service"}
OMV_AVAHIDAEMON_AFPSERVICE_PORT=${OMV_AVAHIDAEMON_AFPSERVICE_PORT:-"548"}
OMV_AVAHIDAEMON_AFPSERVICE_FINDERICON=${OMV_AVAHIDAEMON_AFPSERVICE_FINDERICON:-"RackMac"}

# Is the service enabled? Announce this service via DNS-SD?
rm -f ${OMV_AVAHIDAEMON_AFPSERVICE}
[ "$(omv_config_get "//services/afp/enable")" != "1" -o "$(omv_config_get "//services/zeroconf/services/service[id='afp']/enable")" != "1" ] && exit 0

# Create '/etc/avahi/services/smb.service' file.
xmlstarlet sel -t \
  -o "<?xml version=\"1.0\" standalone=\"no\"?>" -n \
  -o "<!DOCTYPE service-group SYSTEM \"avahi-service.dtd\">" -n \
  -o "<service-group>" -n \
  -v "concat('  <name replace-wildcards=\"yes\">',//services/zeroconf/services/service[id='afp']/name,'</name>')" -n \
  -o "  <service>" -n \
  -o "    <type>_afpovertcp._tcp</type>" -n \
  -o "    <port>${OMV_AVAHIDAEMON_AFPSERVICE_PORT}</port>" -n \
  -o "  </service>" -n \
  -o "  <service>" -n \
  -o "    <type>_adisk._tcp</type>" -n \
  -o "    <port>9</port>" -n \
  -o "    <txt-record>sys=waMA=0,adVF=0x100</txt-record>" -n \
  -m "//services/afp/shares/share" \
	-i "options/tm[. = '1']" \
	  -v "concat('    <txt-record>dk',position()-1,'=adVN=',name,',adVF=0xa1,adVU=',uuid,'</txt-record>')" -n \
	-b \
  -b \
  -o "  </service>" -n \
  -o "  <service>" -n \
  -o "    <type>_device-info._tcp</type>" -n \
  -o "    <port>0</port>" -n \
  -o "    <txt-record>model=${OMV_AVAHIDAEMON_AFPSERVICE_FINDERICON}</txt-record>" -n \
  -o "  </service>" -n \
  -o "</service-group>" \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_AVAHIDAEMON_AFPSERVICE}
