#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2019 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://de.linwiki.org/wiki/Linuxfibel_-_Netzwerk_Server_-_NFS_Server
# http://wiki.ubuntuusers.de/NFS
# http://www.centos.org/docs/5/html/Deployment_Guide-en-US/s1-nfs-server-config-exports.html
# https://help.ubuntu.com/community/NFSv4Howto
# http://jkossen.nl/2009/05/12/simple-nfsv4-configuration-for-debian-and-ubuntu.html
# http://doc.opensuse.org/products/opensuse/openSUSE/opensuse-reference/cha.nfs.html

# Testing:
# showmount -e <nfs-server>

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_NFSD_DEFAULT=${OMV_NFSD_DEFAULT:-"/run/sysconfig/nfs-utils"}
OMV_NFSD_RPCMOUNTDARGS=${OMV_NFSD_RPCMOUNTDARGS:-"--manage-gids"}
OMV_NFSD_STATDARGS=${OMV_NFSD_STATDARGS:-""}
OMV_NFSD_RPCSVCGSSDARGS=${OMV_NFSD_RPCSVCGSSDARGS:-""}

# Create /run/sysconfig/nfs-utils file.
xmlstarlet sel -t \
  -m "//services/nfs" \
    -o "PIPEFS_MOUNTPOINT=${OMV_NFSD_PIPEFS_MOUNTPOINT}" -n \
    -v "concat('RPCNFSDARGS=\"',numproc,'\"')" -n \
    -o "RPCMOUNTDARGS=\"${OMV_NFSD_RPCMOUNTDARGS}\"" -n \
    -o "STATDARGS=\"${OMV_NFSD_STATDARGS}\"" -n \
    -o "RPCSVCGSSDARGS=\"${OMV_NFSD_RPCSVCGSSDARGS}\"" -n \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_NFSD_DEFAULT}
