#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2011 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_AVAHIDAEMON_AFPSERVICE=${OMV_AVAHIDAEMON_AFPSERVICE:-"/etc/avahi/services/afp.service"}
OMV_AVAHIDAEMON_AFPSERVICE_NAME=${OMV_AVAHIDAEMON_AFPSERVICE_NAME:-"%h - AFP"}
OMV_AVAHIDAEMON_AFPSERVICE_PORT=${OMV_AVAHIDAEMON_AFPSERVICE_PORT:-"548"}
OMV_AVAHIDAEMON_AFPSERVICE_FINDERICON=${OMV_AVAHIDAEMON_AFPSERVICE_FINDERICON:-"RackMac"}

# Is the service enabled?
rm -f ${OMV_AVAHIDAEMON_AFPSERVICE}
[ "$(omv_config_get "//services/afp/enable")" = "0" ] && exit 0

# Create '/etc/avahi/services/smb.service' file.
cat <<EOF > ${OMV_AVAHIDAEMON_AFPSERVICE}
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">${OMV_AVAHIDAEMON_AFPSERVICE_NAME}</name>
  <service>
    <type>_afpovertcp._tcp</type>
    <port>${OMV_AVAHIDAEMON_AFPSERVICE_PORT}</port>
  </service>
  <service>
    <type>_adisk._tcp</type>
    <port>9</port>
    <txt-record>sys=waMA=0,adVF=0x100</txt-record>
EOF

xmlstarlet sel -t -m "//services/afp/shares/share" \
  -v "concat('    &lt;txt-record&gt;dk',position()-1,'=adVF=')" \
  -i "options/tm[. = '1']" -o "0x0081" -b \
  -i "options/tm[. != '1']" -o "0x0001" -b \
  -v "concat(',adVN=',name,',adVU=',uuid)" \
  -o "&lt;/txt-record&gt;" \
  -n \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_AVAHIDAEMON_AFPSERVICE}

cat <<EOF >> ${OMV_AVAHIDAEMON_AFPSERVICE}
  </service>
  <service>
    <type>_device-info._tcp</type>
    <port>0</port>
    <txt-record>model=${OMV_AVAHIDAEMON_AFPSERVICE_FINDERICON}</txt-record>
  </service>
</service-group>
EOF
