#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2011 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_CERTIFICATE_DIR=${OMV_CERTIFICATE_DIR:-"/etc/ssl"}

# Create the certificate files
xmlstarlet sel -t -m "//system/certificates/sslcertificate" \
  -v uuid -i "position() != last()" -n -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc |
  while read uuid; do
	  crtfile="${OMV_CERTIFICATE_DIR}/certs/${uuid}.crt"
	  xmlstarlet sel -t -m "//system/certificates/sslcertificate[uuid='${uuid}']" \
		-v certificate \
		${OMV_CONFIG_FILE} | xmlstarlet unesc > ${crtfile}
	  chmod 0640 ${crtfile}

	  keyfile="${OMV_CERTIFICATE_DIR}/private/${uuid}.key"
	  xmlstarlet sel -t -m "//system/certificates/sslcertificate[uuid='${uuid}']" \
		-v privatekey \
		${OMV_CONFIG_FILE} | xmlstarlet unesc > ${keyfile}
	  chmod 0600 ${keyfile}
  done

# Create symbolic links to files named by the hash values
c_rehash ${OMV_CERTIFICATE_DIR}/certs
