#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2011 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://wiki.ubuntuusers.de/ProFTPD
# http://www.proftpd.de/HowTo-Server-Config.42.0.html
# http://wiki.ubuntu-forum.de/index.php/ProFTPd

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

PROFTPD_CONFIG=${PROFTPD_CONFIG:-"/etc/proftpd/proftpd.conf"}
PROFTPD_EXTENSIONSDIR=${PROFTPD_EXTENSIONSDIR:-"${OMV_SCRIPTS_DIR}/proftpd.d"}
PROFTPD_DEFAULTROOT=${PROFTPD_DEFAULTROOT:-"/home/ftp"}
PROFTPD_DISPLAYLOGIN=${PROFTPD_DISPLAYLOGIN:-"/home/ftp/welcome.msg"}
PROFTPD_USEIPV6=${PROFTPD_USEIPV6:-"on"}
PROFTPD_DEFERWELCOME=${PROFTPD_DEFERWELCOME:-"off"}
PROFTPD_MULTILINERFC2228=${PROFTPD_MULTILINERFC2228:-"on"}
PROFTPD_DEFAULTSERVER=${PROFTPD_DEFAULTSERVER:-"on"}
PROFTPD_SHOWSYMLINKS=${PROFTPD_SHOWSYMLINKS:-"on"}
PROFTPD_TIMEOUTNOTRANSFER=${PROFTPD_TIMEOUTNOTRANSFER:-"600"}
PROFTPD_TIMEOUTSTALLED=${PROFTPD_TIMEOUTSTALLED:-"600"}
PROFTPD_LISTOPTIONS=${PROFTPD_LISTOPTIONS:-"-l"}
PROFTPD_MAXINSTANCES=${PROFTPD_MAXINSTANCES:-"30"}
PROFTPD_DENYFILTER=${PROFTPD_DENYFILTER:-"\*.*/"}
PROFTPD_AUTHORDER=${PROFTPD_AUTHORDER:-"mod_auth_pam.c* mod_auth_unix.c"}
PROFTPD_USER=${PROFTPD_USER:-"proftpd"}
PROFTPD_GROUP=${PROFTPD_GROUP:-"nogroup"}
PROFTPD_UMASK=${PROFTPD_UMASK:-"022 022"}
PROFTPD_USEFTPUSERS=${PROFTPD_USEFTPUSERS:-"off"}
PROFTPD_TIMESGMT=${PROFTPD_TIMESGMT:-"off"}
PROFTPD_DEFAULTTRANSFERMODE=${PROFTPD_DEFAULTTRANSFERMODE:-"ascii"}
PROFTPD_ALLOWOVERWRITE=${PROFTPD_ALLOWOVERWRITE:-"on"}
PROFTPD_DELETEABORTEDSTORES=${PROFTPD_DELETEABORTEDSTORES:-"off"}
PROFTPD_MODQUOTATAB_QUOTAENGINE=${PROFTPD_MODQUOTATAB_QUOTAENGINE:-"off"}
PROFTPD_MODRATIO_RATIOS=${PROFTPD_MODRATIO_RATIOS:-"off"}
PROFTPD_MODFACL_FACLENGINE=${PROFTPD_MODFACL_FACLENGINE:-"on"}
PROFTPD_MODDELAY_DELAYENGINE=${PROFTPD_MODDELAY_DELAYENGINE:-"on"}
PROFTPD_MODCTRLS_CONTROLSENGINE=${PROFTPD_MODCTRLS_CONTROLSENGINE:-"on"}
PROFTPD_MODCTRLS_CONTROLSMAXCLIENTS=${PROFTPD_MODCTRLS_CONTROLSMAXCLIENTS:-"2"}
PROFTPD_MODCTRLS_CONTROLSLOG=${PROFTPD_MODCTRLS_CONTROLSLOG:-"/var/log/proftpd/controls.log"}
PROFTPD_MODCTRLS_CONTROLSINTERVAL=${PROFTPD_MODCTRLS_CONTROLSINTERVAL:-"5"}
PROFTPD_MODCTRLS_CONTROLSSOCKET=${PROFTPD_MODCTRLS_CONTROLSSOCKET:-"/var/run/proftpd/proftpd.sock"}
PROFTPD_MODCTRLSADMIN_ADMINCONTROLSENGINE=${PROFTPD_MODCTRLSADMIN_ADMINCONTROLSENGINE:-"off"}
PROFTPD_MODBAN_BANCONTROLSACLS=${PROFTPD_MODBAN_BANCONTROLSACLS:-"all allow user root"}
PROFTPD_MODBAN_BANLOG=${PROFTPD_MODBAN_BANLOG:-"/var/log/proftpd/ban.log"}
PROFTPD_MODBAN_BANMESSAGE=${PROFTPD_MODBAN_BANMESSAGE:-"Host %a has been banned"}
PROFTPD_MODBAN_BANTABLE=${PROFTPD_MODBAN_BANTABLE:-"/var/run/proftpd/ban.tab"}
PROFTPD_MODTLS_CONFIG=${PROFTPD_MODTLS_CONFIG:-"/etc/proftpd/tls.conf"}
PROFTPD_MODTLS_TLSLOG=${PROFTPD_MODTLS_TLSLOG:-"/var/log/proftpd/tls.log"}
PROFTPD_MODTLS_TLSPROTOCOL=${PROFTPD_MODTLS_TLSPROTOCOL:-"SSLv23"}
PROFTPD_MODTLS_TLSOPTIONS=${PROFTPD_MODTLS_TLSOPTIONS:-"NoCertRequest"}
PROFTPD_MODTLS_TLSRSACERTIFICATEFILE=${PROFTPD_MODTLS_TLSRSACERTIFICATEFILE:-"/etc/ssl/certs/proftpd.crt"}
PROFTPD_MODTLS_TLSRSACERTIFICATEKEYFILE=${PROFTPD_MODTLS_TLSRSACERTIFICATEKEYFILE:-"/etc/ssl/private/proftpd.key"}
PROFTPD_MODTLS_TLSVERIFYCLIENT=${PROFTPD_MODTLS_TLSVERIFYCLIENT:-"off"}
PROFTPD_MODTLS_TLSRENEGOTIATE=${PROFTPD_MODTLS_TLSRENEGOTIATE:-"required off"}

# Create welcome message file
displaylogin=$(omv_config_get "//services/ftp/displaylogin")
if [ -z "${displaylogin}" ]; then
	cat <<EOF > ${PROFTPD_DISPLAYLOGIN}
Welcome user %U@%R to %L FTP server.
The local time is: %T
EOF
else
	echo ${displaylogin} > ${PROFTPD_DISPLAYLOGIN}
fi

# Create /etc/proftpd/proftpd.conf configuration
xmlstarlet sel -t \
  -o "Include /etc/proftpd/modules.conf" -n \
  -o "UseIPv6 ${PROFTPD_USEIPV6}" -n \
  -v "concat('ServerName &quot;',//system/network/hostname,'&quot;')" -n \
  -o "ServerType standalone" -n \
  -o "DeferWelcome ${PROFTPD_DEFERWELCOME}" -n \
  -o "MultilineRFC2228 ${PROFTPD_MULTILINERFC2228}" -n \
  -o "DefaultServer ${PROFTPD_DEFAULTSERVER}" -n \
  -o "ShowSymlinks ${PROFTPD_SHOWSYMLINKS}" -n \
  -o "DisplayLogin ${PROFTPD_DISPLAYLOGIN}" -n \
  -o "DisplayChdir .message true" -n \
  -o "ListOptions &quot;${PROFTPD_LISTOPTIONS}&quot;" -n \
  -o "MaxInstances ${PROFTPD_MAXINSTANCES}" -n \
  -o "DenyFilter ${PROFTPD_DENYFILTER}" -n \
  -o "User ${PROFTPD_USER}" -n \
  -o "Group ${PROFTPD_GROUP}" -n \
  -o "Umask ${PROFTPD_UMASK}" -n \
  -o "UseFtpUsers ${PROFTPD_USEFTPUSERS}" -n \
  -o "DefaultRoot ${PROFTPD_DEFAULTROOT}" -n \
  -o "TimesGMT ${PROFTPD_TIMESGMT}" -n \
  -o "AllowOverwrite ${PROFTPD_ALLOWOVERWRITE}" -n \
  -o "AuthOrder ${PROFTPD_AUTHORDER}" -n \
  -o "DefaultTransferMode ${PROFTPD_DEFAULTTRANSFERMODE}" -n \
  -o "#TransferLog /var/log/proftpd/xferlog" -n \
  -o "#SystemLog /var/log/proftpd/proftpd.log" -n \
  -o "&lt;IfModule mod_facl.c&gt;" -n \
  -o "  FACLEngine ${PROFTPD_MODFACL_FACLENGINE}" -n \
  -o "&lt;/IfModule&gt;" -n \
  -o "&lt;IfModule mod_quotatab.c&gt;" -n \
  -o "  QuotaEngine ${PROFTPD_MODQUOTATAB_QUOTAENGINE}" -n \
  -o "&lt;/IfModule&gt;" -n \
  -o "&lt;IfModule mod_ratio.c&gt;" -n \
  -o "  Ratios ${PROFTPD_MODRATIO_RATIOS}" -n \
  -o "&lt;/IfModule&gt;" -n \
  -o "&lt;IfModule mod_delay.c&gt;" -n \
  -o "  DelayEngine ${PROFTPD_MODDELAY_DELAYENGINE}" -n \
  -o "&lt;/IfModule&gt;" -n \
  -o "&lt;IfModule mod_ctrls.c&gt;" -n \
  -o "  ControlsEngine ${PROFTPD_MODCTRLS_CONTROLSENGINE}" -n \
  -o "  ControlsMaxClients ${PROFTPD_MODCTRLS_CONTROLSMAXCLIENTS}" -n \
  -o "  ControlsLog ${PROFTPD_MODCTRLS_CONTROLSLOG}" -n \
  -o "  ControlsInterval ${PROFTPD_MODCTRLS_CONTROLSINTERVAL}" -n \
  -o "  ControlsSocket ${PROFTPD_MODCTRLS_CONTROLSSOCKET}" -n \
  -o "&lt;/IfModule&gt;" -n \
  -o "&lt;IfModule mod_ctrls_admin.c&gt;" -n \
  -o "  AdminControlsEngine ${PROFTPD_MODCTRLSADMIN_ADMINCONTROLSENGINE}" -n \
  -o "&lt;/IfModule&gt;" -n \
  -m "//services/ftp" \
	  -o "&lt;IfModule mod_ban.c&gt;" -n \
	  -i "count(modules/mod_ban/rule) = 0" -o "  BanEngine off" -n -b \
	  -i "count(modules/mod_ban/rule) > 0" -o "  BanEngine on" -n -b \
	  -o "  BanControlsACLs ${PROFTPD_MODBAN_BANCONTROLSACLS}" -n \
	  -o "  BanLog ${PROFTPD_MODBAN_BANLOG}" -n \
	  -o "  BanMessage ${PROFTPD_MODBAN_BANMESSAGE}" -n \
	  -m "modules/mod_ban/rule" \
		  -v "concat('  BanOnEvent ',event,' ',occurrence,'/',timeinterval,' ',expire)" -n \
	  -b \
	  -o "  BanTable ${PROFTPD_MODBAN_BANTABLE}" -n \
	  -o "&lt;/ifModule&gt;" -n \
	  -i "modules/mod_tls/enable[. = '1']" \
		  -o "Include ${PROFTPD_MODTLS_CONFIG}" -n \
	  -b \
	  -v "concat('Port ',port)" -n \
	  -i "requirevalidshell[. = '0']" -o "RequireValidShell off" -n -b \
	  -i "requirevalidshell[. = '1']" -o "RequireValidShell on" -n -b \
	  -i "identlookups[. = '0']" -o "IdentLookups off" -n -b \
	  -i "identlookups[. = '1']" -o "IdentLookups on" -n -b \
	  -i "usereversedns[. = '0']" -o "UseReverseDNS off" -n -b \
	  -i "usereversedns[. = '1']" -o "UseReverseDNS on" -n -b \
	  -v "concat('TimeoutIdle ',timeoutidle)" -n \
	  -o "TimeoutNoTransfer ${PROFTPD_TIMEOUTNOTRANSFER}" -n \
	  -o "TimeoutStalled ${PROFTPD_TIMEOUTSTALLED}" -n \
	  -i "usepassiveports[. = '1']" -v "concat('PassivePorts ',minpassiveports,' ',maxpassiveports)" -n -b \
	  -i "string-length(masqueradeaddress) > 0" -v "concat('MasqueradeAddress ',masqueradeaddress)" -n -b \
	  -i "limittransferrate[. = '1']" \
		  -i "maxuptransferrate[. > '0']" -v "concat('TransferRate STOR ',maxuptransferrate)" -n -b \
		  -i "maxdowntransferrate[. > '0']" -v "concat('TransferRate RETR ',maxdowntransferrate)" -n -b \
	  -b \
	  -i "rootlogin[. = '1']" -o "RootLogin on" -n -b \
	  -i "allowrestart[. = '1']" \
		  -o "AllowRetrieveRestart on" -n \
		  -o "AllowStoreRestart on" -n \
	  -b \
	  -o "DeleteAbortedStores ${PROFTPD_DELETEABORTEDSTORES}" -n \
	  -i "allowforeignaddress[. = '1']" -o "AllowForeignAddress on" -n -b \
	  -v "concat('MaxClients ',maxclients)" -n \
	  -i "maxconnectionsperhost[. > '0']" -v "concat('MaxConnectionsPerHost ',maxconnectionsperhost)" -n -b \
	  -i "maxloginattempts[. > '0']" -v "concat('MaxLoginAttempts ',maxloginattempts )" -n -b \
	  -i "string-length(extraoptions) > 0" -v extraoptions -n -b \
	  -o "&lt;Directory ${PROFTPD_DEFAULTROOT}&gt;" -n \
	  -o "  HideFiles (welcome.msg)" -n \
	  -o "&lt;/Directory&gt;" -n \
	  -i "anonymous[. = '1']" \
		  -o "&lt;Anonymous ~ftp&gt;" -n \
		  -o "  User ftp" -n \
		  -o "  Group nogroup" -n \
		  -o "  UserAlias anonymous ftp" -n \
		  -o "  DirFakeUser on ftp" -n \
		  -o "  DirFakeGroup on ftp" -n \
		  -o "  RequireValidShell off" -n \
		  -o "  &lt;Directory *&gt;" -n \
		  -o "    HideFiles (welcome.msg)" -n \
		  -o "    HideNoAccess on" -n \
		  -o "    &lt;Limit WRITE&gt;" -n \
		  -o "      DenyAll" -n \
		  -o "    &lt;/Limit&gt;" -n \
		  -o "  &lt;/Directory&gt;" -n \
		  -o "&lt;/Anonymous&gt;" -n \
	  -b \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${PROFTPD_CONFIG}

# Is it allowed to login as superuser directly?
rootlogin=$(omv_config_get "//services/ftp/rootlogin")

# Process FTP shares
index=$(omv_config_get_count "//services/ftp/shares/share")
while [ ${index} -gt 0 ]
do
	limitall_allowuser=""
	limitall_allowgroup=""
	limitread_allowuser=""
	limitread_allowgroup=""

	# Is it allowed to login as superuser directly?
	if [ ${rootlogin} -eq 1 ]; then
		limitall_allowuser="root"
		limitall_allowgroup="root"
	fi

	# Get the shared folder reference and path
	sfref=$(omv_config_get "//services/ftp/shares/share[position()=${index}]/sharedfolderref")
	sfname=$(omv_get_sharedfolder_name "${sfref}")
	sfpath="${PROFTPD_DEFAULTROOT}/${sfname}"

	# Get shared folder user privileges
	privileges=$(xmlstarlet sel -t -m "//system/shares/sharedfolder[uuid='${sfref}']/privileges/privilege[userref]" \
	  -v "concat(perms,'|',//system/usermanagement/users/user[uuid=current()/userref]/name)" -n \
	  ${OMV_CONFIG_FILE} | xmlstarlet unesc)
	for privilege in ${privileges}
	do
		perms=${privilege%|*}
		name=${privilege#*|}
		# Skip 'No access' entries
		[ ${perms} -eq 0 ] && continue
		# Append user to list
		case ${perms} in
		5)
			[ -n "${limitread_allowuser}" ] && limitread_allowuser="${limitread_allowuser},";
			limitread_allowuser="${limitread_allowuser}${name}";;
		7)
			[ -n "${limitall_allowuser}" ] && limitall_allowuser="${limitall_allowuser},";
			limitall_allowuser="${limitall_allowuser}${name}";;
		esac
	done

	# Get shared folder group privileges
	privileges=$(xmlstarlet sel -t -m "//system/shares/sharedfolder[uuid='${sfref}']/privileges/privilege[groupref]" \
	  -v "concat(perms,'|',//system/usermanagement/groups/group[uuid=current()/groupref]/name)" -n \
	  ${OMV_CONFIG_FILE} | xmlstarlet unesc)
	for privilege in ${privileges}
	do
		perms=${privilege%|*}
		name=${privilege#*|}
		# Skip 'No access' entries
		[ ${perms} -eq 0 ] && continue
		# Append group to list
		case ${perms} in
		5)
			[ -n "${limitread_allowgroup}" ] && limitread_allowgroup="${limitread_allowgroup},";
			limitread_allowgroup="${limitread_allowgroup}${name}";;
		7)
			[ -n "${limitall_allowgroup}" ] && limitall_allowgroup="${limitall_allowgroup},";
			limitall_allowgroup="${limitall_allowgroup}${name}";;
		esac
	done

	cat <<EOF >> ${PROFTPD_CONFIG}
<Directory ${sfpath}>
  <Limit ALL>
EOF
	[ -n "${limitall_allowuser}" ] && echo "    AllowUser ${limitall_allowuser}" >> ${PROFTPD_CONFIG}
	[ -n "${limitall_allowgroup}" ] && echo "    AllowGroup ${limitall_allowgroup}" >> ${PROFTPD_CONFIG}
	cat <<EOF >> ${PROFTPD_CONFIG}
    DenyAll
  </Limit>
  <Limit READ DIRS>
EOF
	[ -n "${limitall_allowuser}" ] && echo "    AllowUser ${limitall_allowuser}" >> ${PROFTPD_CONFIG}
	[ -n "${limitall_allowgroup}" ] && echo "    AllowGroup ${limitall_allowgroup}" >> ${PROFTPD_CONFIG}
	[ -n "${limitread_allowuser}" ] && echo "    AllowUser ${limitread_allowuser}" >> ${PROFTPD_CONFIG}
	[ -n "${limitread_allowgroup}" ] && echo "    AllowGroup ${limitread_allowgroup}" >> ${PROFTPD_CONFIG}
	cat <<EOF >> ${PROFTPD_CONFIG}
    DenyAll
  </Limit>
</Directory>
EOF

	index=$(( ${index} - 1 ))
done

# Add additional extensions to the configuration file
run-parts ${PROFTPD_EXTENSIONSDIR}
