#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# https://www.freedesktop.org/software/systemd/man/systemd.mount.html
# https://www.freedesktop.org/software/systemd/man/bootup.html#System%20Manager%20Bootup
# https://copyninja.info/blog/systemd_automount_entry.html
# https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files
# https://utcc.utoronto.ca/~cks/space/blog/linux/SystemdBindMountUnits

# Testing:
# systemctl cat sharedfolders-test1.mount
# systemctl show -p Requires,After sharedfolders-test1.mount

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_SHAREDFOLDERS_DIR=${OMV_SHAREDFOLDERS_DIR:-"/sharedfolders"}
OMV_SYSTEMD_CUSTOM_UNITS_DIR=${OMV_SYSTEMD_CUSTOM_UNITS_DIR:-"/etc/systemd/system"}

# Cleanup existing systemd unit files.
unitfiletpl=$(systemd-escape --path "${OMV_SHAREDFOLDERS_DIR}")
find "${OMV_SYSTEMD_CUSTOM_UNITS_DIR}" -type f -iname "${unitfiletpl}-*.mount" -print0 | xargs -0r rm -f

# Create the systemd unit files.
omv-confdbadm read "conf.system.sharedfolder" |
    jq -r ".[] | .uuid" |
    while read uuid; do
        mntdir=$(omv_get_sharedfolder_mount_dir "${uuid}")
        name=$(omv_get_sharedfolder_name "${uuid}")
        what=$(omv_get_sharedfolder_path "${uuid}")
        where="${OMV_SHAREDFOLDERS_DIR}/${name}"
        unitname=$(systemd-escape --path --suffix=mount "${where}")
        unitfile="${OMV_SYSTEMD_CUSTOM_UNITS_DIR}/${unitname}"

        cat <<EOF > ${unitfile}
# This configuration file is auto-generated.
[Unit]
Description=Mount shared folder ${name} to ${where}
DefaultDependencies=no
After=zfs-mount.service
Wants=sysinit.target
Conflicts=umount.target
RequiresMountsFor=${mntdir}
AssertPathIsDirectory=${OMV_SHAREDFOLDERS_DIR}
AssertPathIsMountPoint=${mntdir}
AssertPathIsDirectory=${what}

[Mount]
What=${what}
Where=${where}
Type=none
Options=bind,nofail

[Install]
WantedBy=basic.target
EOF
    done;
