#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2017 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# https://www.freedesktop.org/software/systemd/man/systemd.mount.html

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_SHAREDFOLDERS_DIR=${OMV_SHAREDFOLDERS_DIR:-"/sharedfolders"}
OMV_SYSTEMD_CUSTOM_UNITS_DIR=${OMV_SYSTEMD_CUSTOM_UNITS_DIR:-"/etc/systemd/system"}

# Cleanup existing systemd unit files.
unitfiletpl=$(systemd-escape --path "${OMV_SHAREDFOLDERS_DIR}")
find "${OMV_SYSTEMD_CUSTOM_UNITS_DIR}" -type f -iname "${unitfiletpl}-*.mount" -print0 | xargs -0r rm -f

# Create the systemd unit files.
omv-confdbadm read "conf.system.sharedfolder" |
    jq -r ".[] | .uuid" |
    while read uuid; do
        name=$(omv_get_sharedfolder_name "${uuid}")
        what=$(omv_get_sharedfolder_path "${uuid}")
        where="${OMV_SHAREDFOLDERS_DIR}/${name}"
        unitname=$(systemd-escape --path --suffix=mount "${where}")
        unitfile="${OMV_SYSTEMD_CUSTOM_UNITS_DIR}/${unitname}"

        cat <<EOF > ${unitfile}
# This configuration file is auto-generated.
[Mount]
What=${what}
Where=${where}
Type=none
Options=bind,nofail

[Install]
WantedBy=multi-user.target
EOF
    done;
