#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault

# Reinstall isc-dhcp-client to force reinstallation of the default
# configuration files. This was overwritten by OpenMediaVault which
# is not necessary anymore now.
OMV_UPGRADE_REINSTALL_PACKAGES=${OMV_UPGRADE_REINSTALL_PACKAGES:-"isc-dhcp-client"}

# Reconfigure various packages.
apt-get --yes --force-yes --purge remove ${OMV_UPGRADE_REINSTALL_PACKAGES}
apt-get --yes --force-yes --reinstall install ${OMV_UPGRADE_REINSTALL_PACKAGES}

exit 0
