#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2016 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_NETATALK_AFP_CONFIG=${OMV_NETATALK_AFP_CONFIG:-"/etc/netatalk/afp.conf"}

[ "$(omv_config_get "//services/afp/enable")" = "0" ] && exit 0

index=$(omv_config_get_count "//services/afp/shares/share")
while [ ${index} -gt 0 ]; do
	# Get the shared folder reference and path
	sfref=$(omv_config_get "//services/afp/shares/share[position()=${index}]/sharedfolderref")
	sfpath=$(omv_get_sharedfolder_path "${sfref}")

	# Process the share privileges. Users with '0 = no permission' are added
	# to 'deny' (to deny access), users with '5 = read and execute'
	# are added to the 'allow'.
	allow=""
	deny=""
	readlist=""
	writelist=""

	# Get shared folder user privileges
	privileges=$(xmlstarlet sel -t \
	  -m "//system/shares/sharedfolder[uuid='${sfref}']/privileges/privilege[type='user']" \
		-v "concat(perms,':',name)" -n \
	  -b \
	  -m "//services/afp/shares/share[position()=${index}]" \
		-i "allowguest[. = '1']" \
		  -i "guestrw[. = '1']" -o "7" -b \
		  -i "guestrw[. = '0']" -o "5" -b \
		  -o ":${OMV_NETATALK_AFPD_GUEST}" -n \
		-b \
		-i "allowguest[. = '0']" \
		  -o "0" -b \
		  -o ":${OMV_NETATALK_AFPD_GUEST}" -n \
		-b \
	  -b \
	  ${OMV_CONFIG_FILE} | xmlstarlet unesc)
	IFS="$(printf '\n+')"
	for privilege in ${privileges}; do
		[ -z "${privilege}" ] && continue
		perms=${privilege%:*}
		name=${privilege#*:}
		# Append user to list
		case ${perms} in
		0)
			# Append user to list of denied users.
			[ -n "${deny}" ] && deny="${deny},";
			deny="${deny}\"${name}\"";
			;;
		5)
			# Append user to list of users with read privileges.
			[ -n "${readlist}" ] && readlist="${readlist},";
			readlist="${readlist}\"${name}\"";
			# Stop the processing of the guest account here.
			#[ "${name}" == "${OMV_NETATALK_AFPD_GUEST}" ] && continue;
			# Append user to list of allowed users.
			#[ -n "${allow}" ] && allow="${allow},";
			#allow="${allow}\"${name}\"";
			;;
		7)
			# Append user to list of users with read/write privileges.
			[ -n "${writelist}" ] && writelist="${writelist},";
			writelist="${writelist}\"${name}\"";
			# Stop the processing of the guest account here.
			#[ "${name}" == "${OMV_NETATALK_AFPD_GUEST}" ] && continue;
			# Append user to list of allowed users.
			#[ -n "${allow}" ] && allow="${allow},";
			#allow="${allow}\"${name}\"";
			;;
		esac
	done
	unset IFS

	# Get shared folder group privileges
	privileges=$(xmlstarlet sel -t -m "//system/shares/sharedfolder[uuid='${sfref}']/privileges/privilege[type='group']" \
	  -v "concat(perms,':',name)" -n \
	  ${OMV_CONFIG_FILE} | xmlstarlet unesc)
	IFS="$(printf '\n+')"
	for privilege in ${privileges}; do
		[ -z "${privilege}" ] && continue
		perms=${privilege%:*}
		name=${privilege#*:}
		# Append group to list
		case ${perms} in
		0)
			[ -n "${deny}" ] && deny="${deny},";
			deny="${deny}@\"${name}\"";
			;;
		5)
			[ -n "${readlist}" ] && readlist="${readlist},";
			readlist="${readlist}@\"${name}\"";
			#[ -n "${allow}" ] && allow="${allow},";
			#allow="${allow}@\"${name}\"";
			;;
		7)
			[ -n "${writelist}" ] && writelist="${writelist},";
			writelist="${writelist}@\"${name}\"";
			#[ -n "${allow}" ] && allow="${allow},";
			#allow="${allow}@\"${name}\"";
			;;
		esac
	done
	unset IFS

	accessrights=""
	#[ -n "${allow}" ] && accessrights="${accessrights} allow:${allow}"
	[ -n "${deny}" ] && accessrights="${accessrights} deny:${deny}"
	[ -n "${readlist}" ] && accessrights="${accessrights} rolist:${readlist}"
	#[ -n "${writelist}" ] && accessrights="${accessrights} rwlist:${writelist}"

	xmlstarlet sel -t -m "//services/afp/shares/share[position()=${index}]" \
	  -n \
	  -v
	  -o "\"${sfpath}\"" \
	  -i "string-length(comment) > 0" -v "concat(' \"',comment,'\"')" -b \
	  -i "string-length(comment) = 0" -v "concat(' \"',name,'\"')" -b \
	  -i "string-length(password) > 0" -v "concat(' password:',password)" -b \
	  -i "volsizelimit > 0" -v "concat(' volsizelimit:',volsizelimit)" -b \
	  -i "not(casefold[. = 'none'])" -v "concat(' casefold:',casefold)" -b \
	  -o " options:" \
	  -m "options/*[. = '1']" \
		  -i "position() != 1" -o "," -b \
		  -v "local-name()" \
	  -b \
	  -o "${accessrights}" \
	  -i "string-length(extraoptions) > 0" -v extraoptions -b \
	  -n \
	  ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_NETATALK_AFP_CONFIG}

	index=$(( ${index} - 1 ))
done
