headers:
  auto_generated: "# This file is auto-generated by openmediavault (https://www.openmediavault.org)"
  warning: "# WARNING: Do not edit this file, your changes will get lost."
  multiline: |
    # This file is auto-generated by openmediavault (https://www.openmediavault.org)
    # WARNING: Do not edit this file, your changes will get lost.
