#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# References:
# http://www.dev-smart.com/archives/54
# http://wherethebitsroam.com/blogs/jeffw/apache-php-fastcgi-and-phpfcgichildren

. /etc/default/locale

export PHPRC="/var/www/openmediavault/cgi"
#export PHP_FCGI_CHILDREN=4
export PHP_FCGI_MAX_REQUESTS=1000
export LANG

exec /usr/lib/cgi-bin/php5
