#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# https://collectd.org/wiki/index.php/Plugin:Disk
# https://github.com/stedolan/jq/wiki/Cookbook

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_COLLECTD_CONFIG_DIR=${OMV_COLLECTD_CONFIG_DIR:-"/etc/collectd/collectd.conf.d"}

# Get the devices containing the file systems.
disks=$(omv-rpc 'FileSystemMgmt' 'enumerateMountedFilesystems' '{"includeroot": true}' |
    jq --raw-output '.[] | .parentdevicefile | tostring | select(startswith("/dev/")) | ltrimstr("/dev/")')

cat <<EOF > "${OMV_COLLECTD_CONFIG_DIR}/disk.conf"
LoadPlugin disk
<Plugin disk>
EOF
for disk in ${disks}; do
	echo "  Disk \"${disk}\"" >> "${OMV_COLLECTD_CONFIG_DIR}/disk.conf"
done
cat <<EOF >> "${OMV_COLLECTD_CONFIG_DIR}/disk.conf"
  IgnoreSelected false
</Plugin>
EOF
