#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_SSH_KEYS_DIR=${OMV_SSH_KEYS_DIR:-"/etc/ssh"}
OMV_SSH_KEY_PREFIX=${OMV_SSH_KEY_PREFIX:-"openmediavault-"}

# Remove all certificate files.
find "${OMV_SSH_KEYS_DIR}" -type f -iname "${OMV_SSH_KEY_PREFIX}*" -print0 | xargs -0r rm -f

# Create the certificate files.
xmlstarlet sel -t \
  -m "//system/certificates/sshcertificate" \
    -v "uuid" -n \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc |
  while read uuid; do
	  privkeyfile="${OMV_SSH_KEYS_DIR}/${OMV_SSH_KEY_PREFIX}${uuid}"
	  xmlstarlet sel -t -m "//system/certificates/sshcertificate[uuid='${uuid}']" \
		-v privatekey \
		${OMV_CONFIG_FILE} | xmlstarlet unesc >"${privkeyfile}"
	  chmod 0600 "${privkeyfile}"

      pubkeyfile="${OMV_SSH_KEYS_DIR}/${OMV_SSH_KEY_PREFIX}${uuid}.pub"
	  xmlstarlet sel -t -m "//system/certificates/sshcertificate[uuid='${uuid}']" \
		-v publickey \
		${OMV_CONFIG_FILE} | xmlstarlet unesc >"${pubkeyfile}"
	  chmod 0644 "${pubkeyfile}"
  done
