#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://linuxwiki.de/OpenSSH
# https://help.ubuntu.com/community/SSH/OpenSSH/Configuring
# https://tools.ietf.org/html/rfc4716

# Converting SSH2 public key (OpenSSH -> RFC4716)
# ssh-keygen -e -f ~/.ssh/id_rsa.pub

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_SSHD_AUTHORIZEDKEYSFILE_DIR=${OMV_SSHD_AUTHORIZEDKEYSFILE_DIR:-"/var/lib/openmediavault/ssh/authorized_keys"}
OMV_SSHD_AUTHORIZEDKEYSFILE_MASK=${OMV_SSHD_AUTHORIZEDKEYSFILE_MASK:-"600"}

# Remove all existing authorized_keys files.
find "${OMV_SSHD_AUTHORIZEDKEYSFILE_DIR}" -type f -print0 | xargs -0r rm -f

# Create the users authorized_keys files.
xmlstarlet sel -t \
  -m "//system/usermanagement/users/user" \
	-v "uuid" -n \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc |
  while read uuid; do
	  name=$(omv_config_get "//system/usermanagement/users/user[uuid='${uuid}']/name")
	  # Check if the user exists.
	  ! omv_user_id_exists "${name}" && continue;
	  # Process all public SSH keys of the user.
	  filename="${OMV_SSHD_AUTHORIZEDKEYSFILE_DIR}/${name}"
	  index=$(omv_config_get_count "//system/usermanagement/users/user[uuid='${uuid}']/sshpubkeys/sshpubkey")
	  touch "${filename}"
	  chmod ${OMV_SSHD_AUTHORIZEDKEYSFILE_MASK} "${filename}"
	  chown "${name}" "${filename}"
	  while [ ${index} -gt 0 ]; do
		  xmlstarlet sel -t -m "//system/usermanagement/users/user[uuid='${uuid}']/sshpubkeys" \
			-v "sshpubkey[position()=${index}]" \
			${OMV_CONFIG_FILE} | xmlstarlet unesc >"${filename}.tmp"
		  ssh-keygen -i -f "${filename}.tmp" >>"${filename}"
		  rm -f "${filename}.tmp"
		  index=$(( ${index} - 1 ))
	  done
  done
