version: "1.0"
type: route
data:
  url: "/services/k8s/settings"
  title: _("Settings")
  editing: true
  notificationTitle: _('Updated Kubernetes settings.')
  component: omv-services-k8s-settings-form-page
