#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://www.korbinian-pauli.de/artikel/mit-lm-sensors-und-rrd-cpu-und-mb-temperatur-uberwachen
# http://blog.stefan-betz.net/2009/1/6/collectd-und-rrdtool-im-einsatz
# http://wiki.lugbz.de/HowTo/SelfMadeMonitoring
# https://collectd.org/wiki/index.php/Inside_the_RRDtool_plugin

# Testing:
# rrdtool info /var/lib/rrdcached/db/localhost/<xxx>/<xxx>.rrd

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_MKCONF_SCRIPTS_DIR=${OMV_MKCONF_SCRIPTS_DIR:-"/usr/share/openmediavault/mkconf"}

OMV_COLLECTD_CONFIG=${OMV_COLLECTD_CONFIG:-"/etc/collectd/collectd.conf"}
OMV_COLLECTD_CONFIG_DIR=${OMV_COLLECTD_CONFIG_DIR:-"/etc/collectd/collectd.conf.d"}
OMV_COLLECTD_PIDFILE=${OMV_COLLECTD_PIDFILE:-"/var/run/collectd.pid"}
OMV_COLLECTD_CRON=${OMV_COLLECTD_CRON:-"/etc/cron.d/openmediavault-mkrrdgraph"}
OMV_COLLECTD_PLUGINS_DIR=${OMV_COLLECTD_PLUGINS_DIR:-"${OMV_MKCONF_SCRIPTS_DIR}/collectd.d"}
OMV_COLLECTD_HOSTNAME=${OMV_COLLECTD_HOSTNAME:-"localhost"}
OMV_COLLECTD_FQDNLOOKUP=${OMV_COLLECTD_FQDNLOOKUP:-"true"}

OMV_MKRRDGRAPH=${OMV_MKRRDGRAPH:-"/usr/sbin/omv-mkrrdgraph"}
OMV_MKRRDGRAPH_INTERVAL=${OMV_MKRRDGRAPH_INTERVAL:-"15"}

mkconf() {
	# Create '/etc/collectd/collectd.conf' file
	cat <<EOF > ${OMV_COLLECTD_CONFIG}
PIDFile "${OMV_COLLECTD_PIDFILE}"
Hostname "${OMV_COLLECTD_HOSTNAME}"
FQDNLookup ${OMV_COLLECTD_FQDNLOOKUP}

<Include "${OMV_COLLECTD_CONFIG_DIR}">
	Filter "*.conf"
</Include>
EOF

	# Remove the cron job.
	rm -f "${OMV_COLLECTD_CRON}"

	# Check if the system performance statistics service is enabled.
	enabled=$(omv_config_get "//system/monitoring/perfstats/enable")
	if omv_checkyesno "${enabled}"; then
		# Create '/etc/cron.d/collectd-rrdgraph' file. Take care about that
		# there will not be send an email if the cron job fails.
		cat <<EOF > ${OMV_COLLECTD_CRON}
# Create graphs every ${OMV_MKRRDGRAPH_INTERVAL} minutes
# m h dom mon dow user    command
*/${OMV_MKRRDGRAPH_INTERVAL} * * * * root ${OMV_MKRRDGRAPH} >/dev/null 2>&1
EOF
		chmod 644 ${OMV_COLLECTD_CRON}
	fi

	# Process the collectd plugins.
	run-parts --exit-on-error ${OMV_COLLECTD_PLUGINS_DIR}
}

case "$1" in
	mkconf|*)
		mkconf
		;;
esac
