#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://technowizah.com/2007/01/debian-how-to-cpu-frequency-management.html
# http://wiki.hetzner.de/index.php/Cool%27n%27Quiet
# http://wiki.ubuntuusers.de/powernowd

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_CPUFREQUTILS_DEFAULT=${OMV_CPUFREQUTILS_DEFAULT:-"/etc/default/cpufrequtils"}
OMV_CPUFREQUTILS_GOVERNOR=${OMV_CPUFREQUTILS_GOVERNOR:-"conservative"}
OMV_CPUFREQUTILS_MAXSPEED=${OMV_CPUFREQUTILS_MAXSPEED:-"0"}
OMV_CPUFREQUTILS_MINSPEED=${OMV_CPUFREQUTILS_MINSPEED:-"0"}
OMV_LOADCPUFREQ_DEFAULT=${OMV_LOADCPUFREQ_DEFAULT:-"/etc/default/loadcpufreq"}

# Create '/etc/default/cpufrequtils' file
xmlstarlet sel -t -m "//system/powermanagement" \
  -i "cpufreq = 0" -o "ENABLE=\"false\"" -n -b \
  -i "cpufreq = 1" -o "ENABLE=\"true\"" -n -b \
  -o "GOVERNOR=\"${OMV_CPUFREQUTILS_GOVERNOR}\"" -n \
  -o "MAX_SPEED=\"${OMV_CPUFREQUTILS_MAXSPEED}\"" -n \
  -o "MIN_SPEED=\"${OMV_CPUFREQUTILS_MINSPEED}\"" \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_CPUFREQUTILS_DEFAULT}

# Create '/etc/default/loadcpufreq' file
xmlstarlet sel -t -m "//system/powermanagement" \
  -i "cpufreq = 0" -o "ENABLE=\"false\"" -b \
  -i "cpufreq = 1" -o "ENABLE=\"true\"" -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_LOADCPUFREQ_DEFAULT}
