#!/bin/bash
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault

OMV_MKCONF_SCRIPTS_DIR=${OMV_MKCONF_SCRIPTS_DIR:-"/usr/share/openmediavault/mkconf"}

OMV_FSTAB_CONFIG=${OMV_FSTAB_CONFIG:-"/etc/fstab"}
OMV_FSTAB_SECTIONNAME=${OMV_FSTAB_SECTIONNAME:-"openmediavault"}
OMV_FSTAB_EXTENSIONS_DIR=${OMV_FSTAB_EXTENSIONS_DIR:-"${OMV_MKCONF_SCRIPTS_DIR}/fstab.d"}

cleanup() {
	rm -f "${tmpfile}"
	exit
}
trap cleanup 0 1 2 5 15
tmpfile=$(mktemp)

# Execute all scripts to build the custom fstab configuration.
echo "# >>> [${OMV_FSTAB_SECTIONNAME}]" > ${tmpfile}
run-parts --exit-on-error "${OMV_FSTAB_EXTENSIONS_DIR}" >> ${tmpfile}
echo "# <<< [${OMV_FSTAB_SECTIONNAME}]" >> ${tmpfile}

# Append the custom fstab configuration if not still present or replace existing one.
if ! grep -E "^# >>> \[${OMV_FSTAB_SECTIONNAME}\]\s*$" ${OMV_FSTAB_CONFIG} >/dev/null; then
	cat ${tmpfile} >> ${OMV_FSTAB_CONFIG}
else
	sed -i -e "/# >>> \[${OMV_FSTAB_SECTIONNAME}\]/r ${tmpfile}" -e "/# >>> \[${OMV_FSTAB_SECTIONNAME}\]/,/# <<< \[${OMV_FSTAB_SECTIONNAME}\]/d" ${OMV_FSTAB_CONFIG}
fi
