#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2015 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_ISSUE_CONFIG=${OMV_ISSUE_CONFIG:-"/etc/issue"}
OMV_ISSUE_APPLY_PRELOGIN_MESSAGE=${OMV_ISSUE_APPLY_PRELOGIN_MESSAGE:-"yes"}

mkconf() {
	# Apply prelogin message?
	! omv_checkyesno "${OMV_ISSUE_APPLY_PRELOGIN_MESSAGE}" && exit 0;

	# Get the product information.
	prdname=$(omv_product_info "name")
	packagename=$(omv_product_info "packagename")
	version=$(dpkg-query -W -f='${Version}' ${packagename})
	versionname=$(omv_product_info "versionname")
	copyright=$(omv_product_info "copyright")
	url=$(omv_product_info "url")

	# Write prelogin message to '/etc/issue' file.
	cat <<EOF > ${OMV_ISSUE_CONFIG}
${prdname} ${version} (${versionname}) \n \l
${copyright}

To manage the system visit the ${prdname} web management
interface via a web browser:

EOF

	ifaces=$(ifquery --list -X lo)
	if [ -n "${ifaces}" ]; then
		for iface in ${ifaces} ; do
			ipaddr=$(omv_get_ipaddr ${iface})
			if [ -n "${ipaddr}" ]; then
				echo "${iface}: ${ipaddr}" >> ${OMV_ISSUE_CONFIG}
			fi
			ipaddr6=$(omv_get_ipaddr6 ${iface})
			if [ -n "${ipaddr6}" ]; then
				echo "${iface}: [${ipaddr6}]" >> ${OMV_ISSUE_CONFIG}
			fi
		done
	else
		echo "No interface(s) available" >> ${OMV_ISSUE_CONFIG}
	fi

	cat <<EOF >> ${OMV_ISSUE_CONFIG}

The default web management interface administrator account has
the username 'admin' and password '$(echo ${prdname} | awk '{print tolower($0)}')'.
It is recommended that you change the password for this account
via the web management interface or using the 'omv-firstaid'
CLI command.

For more information regarding this appliance, please visit
the web site: ${url}

EOF
}

case "$1" in
	mkconf|*)
		mkconf
		;;
esac
