#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Testing:
# rrdtool info /var/lib/rrdcached/db/localhost/<xxx>/<xxx>.rrd

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_RRDCACHED_DEFAULT=${OMV_RRDCACHED_DEFAULT:-"/etc/default/rrdcached"}
OMV_RRDCACHED_PIDFILE=${OMV_RRDCACHED_PIDFILE:-"/var/run/rrdcached.pid"}
OMV_RRDCACHED_SOCKETFILE=${OMV_RRDCACHED_SOCKETFILE:-"/var/run/rrdcached.sock"}
OMV_RRDCACHED_JOURNALDIR=${OMV_RRDCACHED_JOURNALDIR:-"/var/lib/rrdcached/journal/"}
OMV_RRDCACHED_BASEDIR=${OMV_RRDCACHED_BASEDIR:-"/var/lib/rrdcached/db/"}
OMV_RRDCACHED_WRITETIMEOUT=${OMV_RRDCACHED_WRITETIMEOUT:-"900"}
OMV_RRDCACHED_FLUSHINTERVAL=${OMV_RRDCACHED_FLUSHINTERVAL:-"3600"}
OMV_RRDCACHED_BASEOPTIONS=${OMV_RRDCACHED_BASEOPTIONS:-"-B -F -f ${OMV_RRDCACHED_FLUSHINTERVAL}"}

# Create '/etc/default/rrdcached' file
cat <<EOF > ${OMV_RRDCACHED_DEFAULT}
# /etc/default file for RRD cache daemon

# Optional override flush interval, in seconds.
WRITE_TIMEOUT=${OMV_RRDCACHED_WRITETIMEOUT}

# Where database files are placed.  If left unset, the default /tmp will
# be used.  NB: The daemon will reject a directory that has symlinks as
# components.  NB: You may want to have -B in BASE_OPTS.
BASE_PATH=${OMV_RRDCACHED_BASEDIR}

# Where journal files are placed.  If left unset, journaling will
# be disabled.
JOURNAL_PATH=${OMV_RRDCACHED_JOURNALDIR}

# FHS standard placement for process ID file.
PIDFILE=${OMV_RRDCACHED_PIDFILE}

# FHS standard placement for local control socket.
SOCKFILE=${OMV_RRDCACHED_SOCKETFILE}

# Any other options not specifically supported by the script (-P, -f,
# -F, -B).
BASE_OPTIONS="${OMV_RRDCACHED_BASEOPTIONS}"
EOF
