#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2014 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_RSYSLOG_CONFIG=${OMV_RSYSLOG_CONFIG:-"/etc/rsyslog.d/remote.conf"}

xmlstarlet sel -t \
  -i "//system/syslog/remote[enable='1']" \
	  -o "*.* @" \
	  -i "//system/syslog/remote[protocol='tcp']" \
		  -o "@" \
	  -b \
	  -v //system/syslog/remote/host \
	  -i "string-length(//system/syslog/remote/port) > 0" \
		  -v "concat(':',//system/syslog/remote/port)" \
	  -b \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_RSYSLOG_CONFIG}
