#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2014 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://linuxwiki.de/OpenSSH
# https://help.ubuntu.com/community/SSH/OpenSSH/Configuring

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_SSHD_CONFIG=${OMV_SSHD_CONFIG:-"/etc/ssh/sshd_config"}
OMV_SSHD_PROTOCOL=${OMV_SSHD_PROTOCOL:-"2"}
OMV_SSHD_ALLOWGROUPS=${OMV_SSHD_ALLOWGROUPS:-"root ssh"}
OMV_SSHD_SUBSYSTEM_SFTP=${OMV_SSHD_SUBSYSTEM_SFTP:-"/usr/lib/openssh/sftp-server"}
OMV_SSHD_ADDRESSFAMILY=${OMV_SSHD_ADDRESSFAMILY:-"any"}
OMV_SSHD_X11FORWARDING=${OMV_SSHD_X11FORWARDING:-"yes"}
OMV_SSHD_X11DISPLAYOFFSET=${OMV_SSHD_X11DISPLAYOFFSET:-"10"}
OMV_SSHD_USEPRIVILEGESEPARATION=${OMV_SSHD_USEPRIVILEGESEPARATION:-"yes"}
OMV_SSHD_KEYREGENERATIONINTERVAL=${OMV_SSHD_KEYREGENERATIONINTERVAL:-"3600"}
OMV_SSHD_SERVERKEYBITS=${OMV_SSHD_SERVERKEYBITS:-"768"}
OMV_SSHD_SYSLOGFACILITY=${OMV_SSHD_SYSLOGFACILITY:-"AUTH"}
OMV_SSHD_LOGLEVEL=${OMV_SSHD_LOGLEVEL:-"INFO"}
OMV_SSHD_LOGINGRACETIME=${OMV_SSHD_LOGINGRACETIME:-"120"}
OMV_SSHD_STRICTMODES=${OMV_SSHD_STRICTMODES:-"yes"}
OMV_SSHD_RSAAUTHENTICATION=${OMV_SSHD_RSAAUTHENTICATION:-"yes"}
OMV_SSHD_PUBKEYAUTHENTICATION=${OMV_SSHD_PUBKEYAUTHENTICATION:-"yes"}
OMV_SSHD_IGNORERHOSTS=${OMV_SSHD_IGNORERHOSTS:-"yes"}
OMV_SSHD_RHOSTSRSAAUTHENTICATION=${OMV_SSHD_RHOSTSRSAAUTHENTICATION:-"no"}
OMV_SSHD_HOSTBASEDAUTHENTICATION=${OMV_SSHD_HOSTBASEDAUTHENTICATION:-"no"}
OMV_SSHD_PERMITEMPTYPASSWORDS=${OMV_SSHD_PERMITEMPTYPASSWORDS:-"no"}
OMV_SSHD_CHALLENGERESPONSEAUTHENTICATION=${OMV_SSHD_CHALLENGERESPONSEAUTHENTICATION:-"no"}
OMV_SSHD_PRINTMOTD=${OMV_SSHD_PRINTMOTD:-"no"}
OMV_SSHD_PRINTLASTLOG=${OMV_SSHD_PRINTLASTLOG:-"yes"}
OMV_SSHD_TCPKEEPALIVE=${OMV_SSHD_TCPKEEPALIVE:-"yes"}
OMV_SSHD_ACCEPTENV=${OMV_SSHD_ACCEPTENV:-"LANG LC_*"}
OMV_SSHD_USEPAM=${OMV_SSHD_USEPAM:-"yes"}
OMV_SSHD_AUTHORIZEDKEYSFILE_DIR=${OMV_SSHD_AUTHORIZEDKEYSFILE_DIR:-"/var/lib/openmediavault/ssh/authorized_keys"}
OMV_SSHD_AUTHORIZEDKEYSFILE=${OMV_SSHD_AUTHORIZEDKEYSFILE:-".ssh/authorized_keys .ssh/authorized_keys2 ${OMV_SSHD_AUTHORIZEDKEYSFILE_DIR}/%u"}

# Limit connections to IPv4 only if IPv6 is disabled.
if [ ! -f /proc/net/if_inet6 ]; then
	OMV_SSHD_ADDRESSFAMILY="inet"
fi

# Create sshd_config file.
# /etc/ssh/sshd_config from the Debian ssh package has been used
# as template.
xmlstarlet sel -t \
  -o "Protocol ${OMV_SSHD_PROTOCOL}" -n \
  -o "HostKey /etc/ssh/ssh_host_rsa_key" -n \
  -o "HostKey /etc/ssh/ssh_host_dsa_key" -n \
  -o "UsePrivilegeSeparation ${OMV_SSHD_USEPRIVILEGESEPARATION}" -n \
  -o "KeyRegenerationInterval ${OMV_SSHD_KEYREGENERATIONINTERVAL}" -n \
  -o "ServerKeyBits ${OMV_SSHD_SERVERKEYBITS}" -n \
  -o "SyslogFacility ${OMV_SSHD_SYSLOGFACILITY}" -n \
  -o "LogLevel ${OMV_SSHD_LOGLEVEL}" -n \
  -o "LoginGraceTime ${OMV_SSHD_LOGINGRACETIME}" -n \
  -o "StrictModes ${OMV_SSHD_STRICTMODES}" -n \
  -o "RSAAuthentication ${OMV_SSHD_RSAAUTHENTICATION}" -n \
  -o "PubkeyAuthentication ${OMV_SSHD_PUBKEYAUTHENTICATION}" -n \
  -o "IgnoreRhosts ${OMV_SSHD_IGNORERHOSTS}" -n \
  -o "RhostsRSAAuthentication ${OMV_SSHD_RHOSTSRSAAUTHENTICATION}" -n \
  -o "HostbasedAuthentication ${OMV_SSHD_HOSTBASEDAUTHENTICATION}" -n \
  -o "PermitEmptyPasswords ${OMV_SSHD_PERMITEMPTYPASSWORDS}" -n \
  -o "ChallengeResponseAuthentication ${OMV_SSHD_CHALLENGERESPONSEAUTHENTICATION}" -n \
  -o "X11Forwarding ${OMV_SSHD_X11FORWARDING}" -n \
  -o "X11DisplayOffset ${OMV_SSHD_X11DISPLAYOFFSET}" -n \
  -o "PrintMotd ${OMV_SSHD_PRINTMOTD}" -n \
  -o "PrintLastLog ${OMV_SSHD_PRINTLASTLOG}" -n \
  -o "TCPKeepAlive ${OMV_SSHD_TCPKEEPALIVE}" -n \
  -o "AcceptEnv ${OMV_SSHD_ACCEPTENV}" -n \
  -o "Subsystem sftp ${OMV_SSHD_SUBSYSTEM_SFTP}" -n \
  -o "UsePAM ${OMV_SSHD_USEPAM}" -n \
  -o "AllowGroups ${OMV_SSHD_ALLOWGROUPS}" -n \
  -o "AddressFamily ${OMV_SSHD_ADDRESSFAMILY}" -n \
  -m "//services/ssh" \
	  -v "concat('Port ',port)" -n \
	  -i "permitrootlogin = 0" -o "PermitRootLogin no" -n -b \
	  -i "permitrootlogin = 1" -o "PermitRootLogin yes" -n -b \
	  -i "tcpforwarding = 0" -o "AllowTcpForwarding no" -n -b \
	  -i "tcpforwarding = 1" -o "AllowTcpForwarding yes" -n -b \
	  -i "compression = 0" -o "Compression no" -n -b \
	  -i "compression = 1" -o "Compression yes" -n -b \
	  -i "passwordauthentication = 0" -o "PasswordAuthentication no" -n -b \
	  -i "passwordauthentication = 1" -o "PasswordAuthentication yes" -n -b \
	  -i "pubkeyauthentication = 0" -o "PubkeyAuthentication no" -n -b \
	  -i "pubkeyauthentication = 1" \
	    -o "AuthorizedKeysFile ${OMV_SSHD_AUTHORIZEDKEYSFILE}" -n \
	    -o "PubkeyAuthentication yes" -n \
	  -b \
	  -i "string-length(extraoptions) > 0" -v "extraoptions" -n -b \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_SSHD_CONFIG}

# Create the users authorized_keys files.
rm -f ${OMV_SSHD_AUTHORIZEDKEYSFILE_DIR}/*
xmlstarlet sel -t \
  -m "//system/usermanagement/users/user[sshpubkey!='']" \
	-v uuid \
	-i "position() != last()" -n -b \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc |
  while read uuid; do
	  name=$(omv_config_get "//system/usermanagement/users/user[uuid='${uuid}']/name")
	  filename="${OMV_SSHD_AUTHORIZEDKEYSFILE_DIR}/${name}"
	  omv_config_get "//system/usermanagement/users/user[uuid='${uuid}']/sshpubkey" > "${filename}"
	  chown "${name}" "${filename}"
  done
