#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_COLLECTD_CONFIG_DIR=${OMV_COLLECTD_CONFIG_DIR:-"/etc/collectd/collectd.conf.d"}
OMV_NUT_UPSD_PORT=${OMV_NUT_UPSD_PORT:-"3493"}

rm -f "${OMV_COLLECTD_CONFIG_DIR}/nut.conf"
[ "$(omv_config_get "//services/nut/enable")" != "1" ] && exit 0

xmlstarlet sel -t -m "//services/nut" \
  -o "LoadPlugin nut" -n \
  -o "<Plugin nut>" -n \
  -v "concat('  UPS \"',upsname,'@localhost:${OMV_NUT_UPSD_PORT}\"')" -n \
  -o "</Plugin>" -n \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > "${OMV_COLLECTD_CONFIG_DIR}/nut.conf"
