#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_MONIT_SERVICE_FILESYSTEM_CONFIG=${OMV_MONIT_SERVICE_FILESYSTEM_CONFIG:-"/etc/monit/conf.d/openmediavault-filesystem.conf"}
OMV_MONIT_SERVICE_FILESYSTEM_SPACEUSAGE=${OMV_MONIT_SERVICE_FILESYSTEM_SPACEUSAGE:-"85"}

if [ "$(omv_config_get "//system/notification/notifications/notification[id='monitfilesystems']/enable")" = "1" ]; then
	# Monitor root filesystem.
	cat <<EOF > ${OMV_MONIT_SERVICE_FILESYSTEM_CONFIG}
# Alert if disk space of root filesystem gets low
check filesystem rootfs with path /
  if space usage > ${OMV_MONIT_SERVICE_FILESYSTEM_SPACEUSAGE}% for 5 times within 15 cycles
    then alert else if succeeded for 10 cycles then alert

EOF

	# Monitor mounted filesystems.
	xmlstarlet sel -t \
	  -m "//system/fstab/mntent[not(contains(opts,'bind') or contains(opts,'loop'))]" \
		-v "uuid" -n \
	  -b \
	  ${OMV_CONFIG_FILE} | xmlstarlet unesc |
	  while read uuid; do
		  # Get the mount point of the filesystem.
		  dir=$(omv_config_get "//system/fstab/mntent[uuid='${uuid}']/dir")
		  # Generate a unique identifier.
		  checkid=$(echo "${dir}" | tr "/ :" "_")
		  # Note, do not monitor the filesystem space usage for various
		  # types like ISO9660 and UDF because for those filesystems the
		  # usage is always reported as 100% by the 'df' command.
		  xmlstarlet sel -t -m "//system/fstab/mntent[uuid='${uuid}']" \
		    -o "check filesystem filesystem${checkid} with path \"${dir}\"" -n \
			-i "type[.!='iso9660' and .!='udf']" \
			  -o "  if space usage > ${OMV_MONIT_SERVICE_FILESYSTEM_SPACEUSAGE}% for 5 times within 15 cycles" -n \
			  -o "    then alert else if succeeded for 10 cycles then alert" -n \
			  -n \
			-b \
			-o "check program mountpoint${checkid} with path \"/bin/mountpoint '${dir}'\"" -n \
			-o "  if status != 0 then alert" -n \
			${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_MONIT_SERVICE_FILESYSTEM_CONFIG}
	  done
fi
