#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2015 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Testing:
# iptables -A INPUT -p tcp --dport 80 -j DROP
# iptables -A INPUT -p tcp --dport 443 -j DROP

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_MONIT_SERVICE_NGINX_CONFIG=${OMV_MONIT_SERVICE_NGINX_CONFIG:-"/etc/monit/conf.d/openmediavault-nginx.conf"}
OMV_MONIT_SERVICE_NGINX_MODE=${OMV_MONIT_SERVICE_NGINX_MODE:-"active"}

cat <<EOF > ${OMV_MONIT_SERVICE_NGINX_CONFIG}
check process nginx with pidfile /var/run/nginx.pid
  start program = "/etc/init.d/nginx start"
  stop program = "/etc/init.d/nginx stop"
  mode ${OMV_MONIT_SERVICE_NGINX_MODE}
  if cpu is greater than 40% for 2 cycles then alert
  if cpu is greater than 80% for 5 cycles then restart
EOF

# Append additional test cases based on the current configuration.
xmlstarlet sel -t -m "//webadmin" \
  -i "forcesslonly[. = '0']" \
    -v "concat('  if failed host 127.0.0.1 port ',port,' protocol http then restart')" -n \
  -b \
  -i "enablessl[. = '1']" \
    -v "concat('  if failed host 127.0.0.1 port ',sslport,' type tcpssl protocol http then restart')" -n \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_MONIT_SERVICE_NGINX_CONFIG}

# Disable event notifications.
xmlstarlet sel -t -m "//system/email" \
  -i "enable = '1'" \
	-i "//system/notification/notifications/monitprocevents = '0'" \
	  -v "concat('  noalert ',primaryemail)" \
	-b \
  -b \
  -n \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_MONIT_SERVICE_NGINX_CONFIG}
