#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2014 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault

OMV_MONIT_SERVICE_OMVWEBGUI_CONFIG=${OMV_MONIT_SERVICE_OMVWEBGUI_CONFIG:-"/etc/monit/conf.d/openmediavault-webgui.conf"}

cat <<EOF > ${OMV_MONIT_SERVICE_OMVWEBGUI_CONFIG}
# Sometimes it happens that the file permission gets modified
check file php-fcgi with path "/var/www/openmediavault/php-fcgi"
  if failed permission 700 then exec "/bin/chmod 700 /var/www/openmediavault/php-fcgi"

EOF
