#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_MONIT_SERVICE_PHPFPM_CONFIG=${OMV_MONIT_SERVICE_PHPFPM_CONFIG:-"/etc/monit/conf.d/openmediavault-phpfpm.conf"}
OMV_MONIT_SERVICE_PHPFPM_MODE=${OMV_MONIT_SERVICE_PHPFPM_MODE:-"active"}

cat <<EOF > ${OMV_MONIT_SERVICE_PHPFPM_CONFIG}
check process php-fpm with pidfile /var/run/php/php7.0-fpm.pid
  start program = "/bin/systemctl start php7.0-fpm"
  stop program = "/bin/systemctl stop php7.0-fpm"
  mode ${OMV_MONIT_SERVICE_PHPFPM_MODE}
EOF

# Disable event notifications.
xmlstarlet sel -t -m "//system/email" \
  -i "enable = '1'" \
	-i "//system/notification/notifications/notification[id='monitprocevents']/enable = '0'" \
	  -v "concat('  noalert ',primaryemail)" \
	-b \
  -b \
  -n \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_MONIT_SERVICE_PHPFPM_CONFIG}
