#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2015 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_MONIT_SERVICE_RRDCACHED_CONFIG=${OMV_MONIT_SERVICE_RRDCACHED_CONFIG:-"/etc/monit/conf.d/openmediavault-rrdcached.conf"}
OMV_MONIT_SERVICE_RRDCACHED_MODE=${OMV_MONIT_SERVICE_RRDCACHED_MODE:-"active"}

cat <<EOF > ${OMV_MONIT_SERVICE_RRDCACHED_CONFIG}
check process rrdcached with pidfile /var/run/rrdcached.pid
  start program = "/etc/init.d/rrdcached start"
  stop program = "/etc/init.d/rrdcached stop"
  mode ${OMV_MONIT_SERVICE_RRDCACHED_MODE}
EOF

# Disable event notifications.
xmlstarlet sel -t -m "//system/email" \
  -i "enable = '1'" \
	-i "//system/notification/notifications/monitprocevents = '0'" \
	  -v "concat('  noalert ',primaryemail)" \
	-b \
  -b \
  -n \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_MONIT_SERVICE_RRDCACHED_CONFIG}
