#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2014 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_MONIT_CONFIG=${OMV_MONIT_CONFIG:-"/etc/monit/monitrc"}
OMV_MONIT_SERVICE_SYSTEM_MEMORYUSAGE=${OMV_MONIT_SERVICE_SYSTEM_MEMORYUSAGE:-"90"}
OMV_MONIT_SERVICE_SYSTEM_CPUUSAGE_USER=${OMV_MONIT_SERVICE_SYSTEM_CPUUSAGE_USER:-"95"}
OMV_MONIT_SERVICE_SYSTEM_CPUUSAGE_SYSTEM=${OMV_MONIT_SERVICE_SYSTEM_CPUUSAGE_SYSTEM:-"95"}
OMV_MONIT_SERVICE_SYSTEM_CPUUSAGE_WAIT=${OMV_MONIT_SERVICE_SYSTEM_CPUUSAGE_WAIT:-"95"}
OMV_MONIT_SERVICE_SYSTEM_LOADAVG_1MIN_MULT=${OMV_MONIT_SERVICE_SYSTEM_LOADAVG_1MIN_MULT:-"2"}
OMV_MONIT_SERVICE_SYSTEM_LOADAVG_1MIN_CYCLES=${OMV_MONIT_SERVICE_SYSTEM_LOADAVG_1MIN_CYCLES:-"3"}
OMV_MONIT_SERVICE_SYSTEM_LOADAVG_5MIN_MULT=${OMV_MONIT_SERVICE_SYSTEM_LOADAVG_5MIN_MULT:-"1"}
OMV_MONIT_SERVICE_SYSTEM_LOADAVG_5MIN_CYCLES=${OMV_MONIT_SERVICE_SYSTEM_LOADAVG_5MIN_CYCLES:-"3"}

cat <<EOF >> ${OMV_MONIT_CONFIG}
check system localhost
EOF

# Monitor load average.
if [ "$(omv_config_get "//system/notification/notifications/monitloadavg")" = "1" ]; then
	# Get the number of CPU's
	numcpu=$(grep -ci processor /proc/cpuinfo)

	cat <<EOF >> ${OMV_MONIT_CONFIG}
  if loadavg (1min) > $(expr ${numcpu} \* ${OMV_MONIT_SERVICE_SYSTEM_LOADAVG_1MIN_MULT}) for ${OMV_MONIT_SERVICE_SYSTEM_LOADAVG_1MIN_CYCLES} cycles then alert
  if loadavg (5min) > $(expr ${numcpu} \* ${OMV_MONIT_SERVICE_SYSTEM_LOADAVG_5MIN_MULT}) for ${OMV_MONIT_SERVICE_SYSTEM_LOADAVG_5MIN_CYCLES} cycles then alert
EOF
fi

# Monitor memory usage.
if [ "$(omv_config_get "//system/notification/notifications/monitmemoryusage")" = "1" ]; then
	cat <<EOF >> ${OMV_MONIT_CONFIG}
  if memory usage > ${OMV_MONIT_SERVICE_SYSTEM_MEMORYUSAGE}% then alert
EOF
fi

# Monitor CPU usage.
if [ "$(omv_config_get "//system/notification/notifications/monitcpuusage")" = "1" ]; then
	cat <<EOF >> ${OMV_MONIT_CONFIG}
  if cpu usage (user) > ${OMV_MONIT_SERVICE_SYSTEM_CPUUSAGE_USER}% then alert
  if cpu usage (system) > ${OMV_MONIT_SERVICE_SYSTEM_CPUUSAGE_SYSTEM}% then alert
  if cpu usage (wait) > ${OMV_MONIT_SERVICE_SYSTEM_CPUUSAGE_WAIT}% then alert
EOF
fi
