#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_COLLECTD_CONFIG_DIR=${OMV_COLLECTD_CONFIG_DIR:-"/etc/collectd/collectd.conf.d"}

IFACE=$(xmlstarlet sel -t \
  -m "//system/network/interfaces/interface[type='ethernet' or type='wireless']" \
	-i "count(//system/network/interfaces/interface/slaves[contains(.,current()/devicename)]) = 0" \
		-v "concat(devicename,' ')" \
	-b \
  -b \
  -m "//system/network/interfaces/interface[type='bond' or type='vlan']" \
	-v "concat(devicename,' ')" \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc)

cat <<EOF > "${OMV_COLLECTD_CONFIG_DIR}/interface.conf"
LoadPlugin interface
<Plugin interface>
EOF
for devicename in ${IFACE}; do
	echo "  Interface \"${devicename}\"" >> "${OMV_COLLECTD_CONFIG_DIR}/interface.conf"
done
cat <<EOF >> "${OMV_COLLECTD_CONFIG_DIR}/interface.conf"
  IgnoreSelected false
</Plugin>
EOF
