#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_RRDCACHED_SOCKETFILE=${OMV_RRDCACHED_SOCKETFILE:-"/var/run/rrdcached.sock"}
OMV_RRDCACHED_BASEDIR=${OMV_RRDCACHED_BASEDIR:-"/var/lib/rrdcached/db/"}

OMV_COLLECTD_CONFIG_DIR=${OMV_COLLECTD_CONFIG_DIR:-"/etc/collectd/collectd.conf.d"}
OMV_COLLECTD_RRDCACHED_CREATEFILES=${OMV_COLLECTD_RRDCACHED_CREATEFILES:-"true"}
OMV_COLLECTD_RRDCACHED_COLLECTSTATISTICS=${OMV_COLLECTD_RRDCACHED_COLLECTSTATISTICS:-"true"}

cat <<EOF > "${OMV_COLLECTD_CONFIG_DIR}/rrdcached.conf"
LoadPlugin rrdcached
<Plugin rrdcached>
  DaemonAddress "unix:${OMV_RRDCACHED_SOCKETFILE}"
  DataDir "${OMV_RRDCACHED_BASEDIR}"
  CreateFiles ${OMV_COLLECTD_RRDCACHED_CREATEFILES}
  CollectStatistics ${OMV_COLLECTD_RRDCACHED_COLLECTSTATISTICS}
</Plugin>
EOF
