#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_COLLECTD_CONFIG_DIR=${OMV_COLLECTD_CONFIG_DIR:-"/etc/collectd/collectd.conf.d"}
OMV_COLLECTD_UNIXSOCK_SOCKETFILE=${OMV_COLLECTD_UNIXSOCK_SOCKETFILE:-"/var/run/collectd.socket"}
OMV_COLLECTD_UNIXSOCK_SOCKETGROUP=${OMV_COLLECTD_UNIXSOCK_SOCKETGROUP:-"root"}
OMV_COLLECTD_UNIXSOCK_SOCKETPERMS=${OMV_COLLECTD_UNIXSOCK_SOCKETPERMS:-"0660"}

cat <<EOF > "${OMV_COLLECTD_CONFIG_DIR}/unixsock.conf"
LoadPlugin unixsock
<Plugin unixsock>
  SocketFile "${OMV_COLLECTD_UNIXSOCK_SOCKETFILE}"
  SocketGroup "${OMV_COLLECTD_UNIXSOCK_SOCKETGROUP}"
  SocketPerms "${OMV_COLLECTD_UNIXSOCK_SOCKETPERMS}"
</Plugin>
EOF
