#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2014 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

. /usr/share/debconf/confmodule

# Force grub to use the same storage device on which the operating
# system was installed when it was manually chosen.
db_get partman-auto/select_disk
if [ -n "${RET}" ]; then
	bootdev=$(cat ${RET}/device)
	logger -t partman "Using '${bootdev}' for grub installation"
	db_set grub-installer/bootdev ${bootdev}
	db_fset grub-installer/bootdev seen true
fi

exit 0
