version: "1.0"
type: navigation-item
data:
  path: "system.updatemgmt.settings.sources"
  position: 15
  text: _("Other Software")
  icon: mdi:source-repository
  url: "/system/updatemgmt/settings/sources"
