#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2019 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://www.postfix.org/TLS_README.html
# https://en.wikipedia.org/wiki/SMTPS
# http://blog.mailgun.com/25-465-587-what-port-should-i-use/

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_POSTFIX_MAIN_CONFIG=${OMV_POSTFIX_MAIN_CONFIG:-"/etc/postfix/main.cf"}
OMV_POSTFIX_MAIN_MYDESTINATION=${OMV_POSTFIX_MAIN_MYDESTINATION:-""}
OMV_POSTFIX_MAIN_INET_INTERFACES=${OMV_POSTFIX_MAIN_INET_INTERFACES:-"localhost"}
OMV_POSTFIX_MAIN_SENDER_CANONICAL_MAPS=${OMV_POSTFIX_MAIN_SENDER_CANONICAL_MAPS:-"/etc/postfix/sender_canonical"}
OMV_POSTFIX_MAIN_SENDER_BCC_MAPS=${OMV_POSTFIX_MAIN_SENDER_BCC_MAPS:-"/etc/postfix/sender_bcc"}
OMV_POSTFIX_MAIN_RECIPIENT_CANONICAL_MAPS=${OMV_POSTFIX_MAIN_RECIPIENT_CANONICAL_MAPS:-"/etc/postfix/recipient_canonical"}
OMV_POSTFIX_MAIN_RECIPIENT_BCC_MAPS=${OMV_POSTFIX_MAIN_RECIPIENT_BCC_MAPS:-"/etc/postfix/recipient_bcc"}
OMV_POSTFIX_MAIN_SMTP_SASL_AUTH_ENABLE=${OMV_POSTFIX_MAIN_SMTP_SASL_AUTH_ENABLE:-"yes"}
OMV_POSTFIX_MAIN_SMTP_SASL_SECURITY_OPTIONS=${OMV_POSTFIX_MAIN_SMTP_SASL_SECURITY_OPTIONS:-"noanonymous"}
OMV_POSTFIX_MAIN_SMTP_SASL_PASSWORD_MAPS=${OMV_POSTFIX_MAIN_SMTP_SASL_PASSWORD_MAPS:-"/etc/postfix/sasl_passwd"}
OMV_POSTFIX_MAIN_SMTP_SASL_MECHANISM_FILTER=${OMV_POSTFIX_MAIN_SMTP_SASL_MECHANISM_FILTER:-""}
OMV_POSTFIX_MAIN_SMTP_TLS_SECURITY_LEVEL=${OMV_POSTFIX_MAIN_SMTP_TLS_SECURITY_LEVEL:-"encrypt"}
OMV_POSTFIX_MAIN_SMTP_TLS_WRAPPERMODE=${OMV_POSTFIX_MAIN_SMTP_TLS_WRAPPERMODE:-"yes"}
OMV_POSTFIX_MAIN_SMTP_TLS_CAFILE=${OMV_POSTFIX_MAIN_SMTP_TLS_CAFILE:-"/etc/ssl/certs/ca-certificates.crt"}
OMV_POSTFIX_MAIN_SMTP_TLS_CAPATH=${OMV_POSTFIX_MAIN_SMTP_TLS_CAPATH:-"/etc/ssl/certs"}
OMV_POSTFIX_MAIN_SMTP_HEADER_CHECKS=${OMV_POSTFIX_MAIN_SMTP_HEADER_CHECKS:-"/etc/postfix/smtp_header_checks"}
OMV_POSTFIX_MAIN_TRANSPORT_MAPS=${OMV_POSTFIX_MAIN_TRANSPORT_MAPS:-"/etc/postfix/transport"}

# Create '/etc/postfix/main.cf' configuration file.
xmlstarlet sel -t -m "//system/email" \
  -m "//system/network/dns" \
    -i "string-length(domainname) > 0" -v "concat('mydomain = ',domainname)" -n -b \
  -b \
  -o "mydestination = ${OMV_POSTFIX_MAIN_MYDESTINATION}" -n \
  -o "inet_interfaces = ${OMV_POSTFIX_MAIN_INET_INTERFACES}" -n \
  -v "concat('relayhost = ',server,':',port)" -n \
  -o "sender_canonical_maps = regexp:${OMV_POSTFIX_MAIN_SENDER_CANONICAL_MAPS}" -n \
  -o "sender_bcc_maps = hash:${OMV_POSTFIX_MAIN_SENDER_BCC_MAPS}" -n \
  -o "recipient_canonical_maps = hash:${OMV_POSTFIX_MAIN_RECIPIENT_CANONICAL_MAPS}" -n \
  -o "recipient_bcc_maps = hash:${OMV_POSTFIX_MAIN_RECIPIENT_BCC_MAPS}" -n \
  -i "authentication[enable = '1']" \
    -o "smtp_sasl_auth_enable = ${OMV_POSTFIX_MAIN_SMTP_SASL_AUTH_ENABLE}" -n \
    -o "smtp_sasl_security_options = ${OMV_POSTFIX_MAIN_SMTP_SASL_SECURITY_OPTIONS}" -n \
    -o "smtp_sasl_password_maps = hash:${OMV_POSTFIX_MAIN_SMTP_SASL_PASSWORD_MAPS}" -n \
    -o "smtp_sasl_mechanism_filter = ${OMV_POSTFIX_MAIN_SMTP_SASL_MECHANISM_FILTER}" -n \
  -b \
  -i "tls[. = '1']" \
    -i "port[. = '465']" \
      -o "smtp_tls_wrappermode = ${OMV_POSTFIX_MAIN_SMTP_TLS_WRAPPERMODE}" -n \
    -b \
    -o "smtp_tls_security_level = ${OMV_POSTFIX_MAIN_SMTP_TLS_SECURITY_LEVEL}" -n \
    -o "smtp_tls_CAfile = ${OMV_POSTFIX_MAIN_SMTP_TLS_CAFILE}" -n \
    -o "smtp_tls_CApath = ${OMV_POSTFIX_MAIN_SMTP_TLS_CAPATH}" -n \
  -b \
  -o "smtp_header_checks = regexp:${OMV_POSTFIX_MAIN_SMTP_HEADER_CHECKS}" -n \
  -o "transport_maps = hash:${OMV_POSTFIX_MAIN_TRANSPORT_MAPS}" -n \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_POSTFIX_MAIN_CONFIG}

if ! omv_is_ipv6_enabled; then
  cat <<EOF >> ${OMV_POSTFIX_MAIN_CONFIG}
inet_protocols = ipv4
EOF
fi

exit 0
