#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_POSTFIX_MASTER_CONFIG=${OMV_POSTFIX_MASTER_CONFIG:-"/etc/postfix/master.cf"}
OMV_POSTFIX_MASTER_NOTIFICATION_RUNNER=${OMV_POSTFIX_MASTER_NOTIFICATION_RUNNER:-"/usr/share/openmediavault/notification/postfix-runner.sh"}

# Create '/etc/postfix/master.cf' configuration file.
xmlstarlet sel -t -m "//system/email" \
  -o "# ==========================================================================" -n \
  -o "# service type  private unpriv  chroot  wakeup  maxproc command + args" -n \
  -o "#               (yes)   (yes)   (yes)   (never) (100)" -n \
  -o "# ==========================================================================" -n \
  -o "smtp      inet  n       -       -       -       -       smtpd" -n \
  -o "pickup    unix  n       -       -       60      1       pickup" -n \
  -o "cleanup   unix  n       -       -       -       0       cleanup" -n \
  -o "qmgr      unix  n       -       n       300     1       qmgr" -n \
  -o "tlsmgr    unix  -       -       -       1000?   1       tlsmgr" -n \
  -o "rewrite   unix  -       -       -       -       -       trivial-rewrite" -n \
  -o "bounce    unix  -       -       -       -       0       bounce" -n \
  -o "defer     unix  -       -       -       -       0       bounce" -n \
  -o "trace     unix  -       -       -       -       0       bounce" -n \
  -o "verify    unix  -       -       -       -       1       verify" -n \
  -o "flush     unix  n       -       -       1000?   0       flush" -n \
  -o "proxymap  unix  -       -       n       -       -       proxymap" -n \
  -o "proxywrite unix -       -       n       -       1       proxymap" -n \
  -o "smtp      unix  -       -       -       -       -       smtp" -n \
  -o "relay     unix  -       -       -       -       -       smtp" -n \
  -o "showq     unix  n       -       -       -       -       showq" -n \
  -o "error     unix  -       -       -       -       -       error" -n \
  -o "retry     unix  -       -       -       -       -       error" -n \
  -o "discard   unix  -       -       -       -       -       discard" -n \
  -o "local     unix  -       n       n       -       -       local" -n \
  -o "virtual   unix  -       n       n       -       -       virtual" -n \
  -o "lmtp      unix  -       -       -       -       -       lmtp" -n \
  -o "anvil     unix  -       -       -       -       1       anvil" -n \
  -o "scache    unix  -       -       -       -       1       scache" -n \
  -o "omvnotificationfilter unix  -       n       n       -       -       pipe flags=qX user=nobody argv=${OMV_POSTFIX_MASTER_NOTIFICATION_RUNNER} \${sender}" \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_POSTFIX_MASTER_CONFIG}

exit 0
