#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://serverfault.com/a/650176
# https://serverfault.com/questions/312940/rewrite-recipient-of-all-except-one-recipient-outgoing-e-mail
# https://wiki.ubuntuusers.de/Postfix/Erweiterte_Konfiguration
# https://www.unixwitch.de/de/sysadmin/tools/postfix

# Testing:
# echo "test" | mail -s "test" root
# postmap -fq "<USER>" regexp:/etc/postfix/sender_canonical
# postmap -fq "<USER>" regexp:/etc/postfix/recipient_canonical

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_POSTFIX_MAIN_SENDER_CANONICAL_MAPS=${OMV_POSTFIX_MAIN_SENDER_CANONICAL_MAPS:-"/etc/postfix/sender_canonical"}
OMV_POSTFIX_MAIN_SENDER_BCC_MAPS=${OMV_POSTFIX_MAIN_SENDER_BCC_MAPS:-"/etc/postfix/sender_bcc"}
OMV_POSTFIX_MAIN_RECIPIENT_CANONICAL_MAPS=${OMV_POSTFIX_MAIN_RECIPIENT_CANONICAL_MAPS:-"/etc/postfix/recipient_canonical"}
OMV_POSTFIX_MAIN_RECIPIENT_BCC_MAPS=${OMV_POSTFIX_MAIN_RECIPIENT_BCC_MAPS:-"/etc/postfix/recipient_bcc"}
OMV_POSTFIX_MAIN_SMTP_SASL_PASSWORD_MAPS=${OMV_POSTFIX_MAIN_SMTP_SASL_PASSWORD_MAPS:-"/etc/postfix/sasl_passwd"}
OMV_POSTFIX_MAIN_SMTP_HEADER_CHECKS=${OMV_POSTFIX_MAIN_SMTP_HEADER_CHECKS:-"/etc/postfix/smtp_header_checks"}
OMV_POSTFIX_MAIN_TRANSPORT_MAPS=${OMV_POSTFIX_MAIN_TRANSPORT_MAPS:-"/etc/postfix/transport"}

# Ensure that various required directories exist.
[ ! -e "/var/spool/postfix/public/pickup" ] &&  mkfifo /var/spool/postfix/public/pickup

# Build the full qualified domain name based on the network configuration.
# - host01
# - host02.openmediavault.org
fqdn=$(xmlstarlet sel -t -m "//system/network/dns" \
  -v "hostname" \
  -i "string-length(domainname) > 0" -v "concat('.',domainname)" -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc)

# Required in some postfix configuration files.
# - host01.localdomain
# - host02.openmediavault.org
myhostname=$(xmlstarlet sel -t -m "//system/network/dns" \
  -v "hostname" \
  -i "string-length(domainname) > 0" -v "concat('.',domainname)" -b \
  -i "string-length(domainname) = 0" -o ".localdomain" -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc)

# Create the '/etc/postfix/sasl_passwd' configuration file.
xmlstarlet sel -t -m "//system/email" \
  -i "authentication[enable = '1']" \
    -v "concat(server,':',port,' ',authentication/username,':',authentication/password)" -n \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_POSTFIX_MAIN_SMTP_SASL_PASSWORD_MAPS}
chown root:root ${OMV_POSTFIX_MAIN_SMTP_SASL_PASSWORD_MAPS}
chmod 0600 ${OMV_POSTFIX_MAIN_SMTP_SASL_PASSWORD_MAPS}
postmap ${OMV_POSTFIX_MAIN_SMTP_SASL_PASSWORD_MAPS}

# Create the '/etc/postfix/recipient_canonical' configuration file. Add a
# catch-all recipient, thus all emails send to an user/address not existing
# will be redirected to the configured primary recipient address.
xmlstarlet sel -t -m "//system/email" \
  -i "enable[. = '1']" \
    -v "concat('root ',primaryemail)" -n \
    -m "//system/usermanagement/users/user[email != '']" \
      -v "concat(name,' ',email)" -n \
    -b \
    -v "concat('@${myhostname} ',primaryemail)" -n \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_POSTFIX_MAIN_RECIPIENT_CANONICAL_MAPS}
chown root:root ${OMV_POSTFIX_MAIN_RECIPIENT_CANONICAL_MAPS}
chmod 0600 ${OMV_POSTFIX_MAIN_RECIPIENT_CANONICAL_MAPS}
postmap ${OMV_POSTFIX_MAIN_RECIPIENT_CANONICAL_MAPS}

# Create the '/etc/postfix/sender_canonical' configuration file. Rewrite all
# outgoing emails with the configured sender address, otherwise the SMTP relay
# will bounce them, e.g.
# postfix/smtp[xxxxx]: XXXXXXXXXX: to=<abc@xyz.localdomain>,
#   orig_to=<test>, relay=mail.gmx.net[x.x.x.x]:25, delay=1,
#   delays=0.02/0.02/0.93/0.06, dsn=5.7.0, status=bounced (host
#   mail.gmx.net[x.x.x.x] said: 550 5.7.0 Sender address does not belong to
#   logged in user {mp030} (in reply to MAIL FROM command))
xmlstarlet sel -t -m "//system/email" \
  -i "enable[. = '1']" \
    -v "concat('/.+/ ',sender)" -n \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_POSTFIX_MAIN_SENDER_CANONICAL_MAPS}
chown root:root ${OMV_POSTFIX_MAIN_SENDER_CANONICAL_MAPS}
chmod 0600 ${OMV_POSTFIX_MAIN_SENDER_CANONICAL_MAPS}
postmap ${OMV_POSTFIX_MAIN_SENDER_CANONICAL_MAPS}

# Create the '/etc/postfix/recipient_bcc' configuration file.
# BCC (blind carbon-copy) all emails send to the primary email address to
# the given secondary email address. Do not use 'sender_bcc_maps' for that,
# otherwise all emails, including local users, will be sent, too.
xmlstarlet sel -t -m "//system/email" \
  -i "enable[. = '1'] and string-length(secondaryemail) > 0" \
    -v "concat(primaryemail,' ',secondaryemail)" -n \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_POSTFIX_MAIN_RECIPIENT_BCC_MAPS}
chown root:root ${OMV_POSTFIX_MAIN_RECIPIENT_BCC_MAPS}
chmod 0600 ${OMV_POSTFIX_MAIN_RECIPIENT_BCC_MAPS}
postmap ${OMV_POSTFIX_MAIN_RECIPIENT_BCC_MAPS}

# Create the '/etc/postfix/sender_bcc' configuration file.
# BCC (blind carbon-copy) all emails to the notification framework.
xmlstarlet sel -t -m "//system/email" \
  -i "enable[. = '1']" \
    -v "concat(sender,' openmediavault-notification@localhost.localdomain')" -n \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_POSTFIX_MAIN_SENDER_BCC_MAPS}
chown root:root ${OMV_POSTFIX_MAIN_SENDER_BCC_MAPS}
chmod 0600 ${OMV_POSTFIX_MAIN_SENDER_BCC_MAPS}
postmap ${OMV_POSTFIX_MAIN_SENDER_BCC_MAPS}

# Create the '/etc/postfix/smtp_header_checks' configuration file.
cat <<EOF > ${OMV_POSTFIX_MAIN_SMTP_HEADER_CHECKS}
# Append the hostname to the email subject
/^Subject: (.*)/ REPLACE Subject: [${fqdn}] \${1}
EOF
chown root:root ${OMV_POSTFIX_MAIN_SMTP_HEADER_CHECKS}
chmod 0600 ${OMV_POSTFIX_MAIN_SMTP_HEADER_CHECKS}

# Create the '/etc/postfix/transport' configuration file.
cat <<EOF > ${OMV_POSTFIX_MAIN_TRANSPORT_MAPS}
openmediavault-notification@localhost.localdomain omvnotificationfilter:
EOF
chown root:root ${OMV_POSTFIX_MAIN_TRANSPORT_MAPS}
chmod 0600 ${OMV_POSTFIX_MAIN_TRANSPORT_MAPS}
postmap ${OMV_POSTFIX_MAIN_TRANSPORT_MAPS}

exit 0
