#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2016 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_POSTFIX_MAIN_SENDER_CANONICAL_MAPS=${OMV_POSTFIX_MAIN_SENDER_CANONICAL_MAPS:-"/etc/postfix/sender_canonical"}
OMV_POSTFIX_MAIN_RECIPIENT_BCC_MAPS=${OMV_POSTFIX_MAIN_RECIPIENT_BCC_MAPS:-"/etc/postfix/recipient_bcc"}
OMV_POSTFIX_MAIN_SMTP_GENERIC_MAPS=${OMV_POSTFIX_MAIN_SMTP_GENERIC_MAPS:-"/etc/postfix/generic"}
OMV_POSTFIX_MAIN_SMTP_SASL_PASSWORD_MAPS=${OMV_POSTFIX_MAIN_SMTP_SASL_PASSWORD_MAPS:-"/etc/postfix/sasl_passwd"}
OMV_POSTFIX_MAIN_SMTP_HEADER_CHECKS=${OMV_POSTFIX_MAIN_SMTP_HEADER_CHECKS:-"/etc/postfix/smtp_header_checks"}
OMV_POSTFIX_MAIN_TRANSPORT_MAPS=${OMV_POSTFIX_MAIN_TRANSPORT_MAPS:-"/etc/postfix/transport"}

# Ensure that various required directories exist.
[ ! -e "/var/spool/postfix/public/pickup" ] &&  mkfifo /var/spool/postfix/public/pickup

# Build the full qualified domain name based on the network configuration.
fqdn=$(xmlstarlet sel -t -m "//system/network" \
  -v "hostname" \
  -i "string-length(domainname) > 0" -v "concat('.',domainname)" \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc)

# Create the '/etc/postfix/sasl_passwd' configuration file.
xmlstarlet sel -t -m "//system/email" \
  -i "authentication[enable = '1']" \
    -v "concat(server,':',port,' ',authentication/username,':',authentication/password)" -n \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_POSTFIX_MAIN_SMTP_SASL_PASSWORD_MAPS}
chown root:root ${OMV_POSTFIX_MAIN_SMTP_SASL_PASSWORD_MAPS}
chmod 0600 ${OMV_POSTFIX_MAIN_SMTP_SASL_PASSWORD_MAPS}
postmap ${OMV_POSTFIX_MAIN_SMTP_SASL_PASSWORD_MAPS}

# Create the '/etc/postfix/generic' configuration file. Add a catch-all
# recipient, thus all emails send to an user/address not existing will be
# redirected to the configured primary recipient address.
xmlstarlet sel -t \
  -i "//system/email/enable[. = '1']" \
	-v "concat('root ',//system/email/primaryemail)" -n \
	-m "//system/usermanagement/users/user[email != '']" \
	  -v "concat(name,' ',email)" -n \
	-b \
	-v "concat('@${fqdn} ',//system/email/primaryemail)" \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_POSTFIX_MAIN_SMTP_GENERIC_MAPS}
chown root:root ${OMV_POSTFIX_MAIN_SMTP_GENERIC_MAPS}
chmod 0600 ${OMV_POSTFIX_MAIN_SMTP_GENERIC_MAPS}
postmap ${OMV_POSTFIX_MAIN_SMTP_GENERIC_MAPS}

# Create the '/etc/postfix/sender_canonical' configuration file. Rewrite all
# outgoing emails with the configured sender address, otherwise the SMTP relay
# will bounce them, e.g.
# postfix/smtp[xxxxx]: XXXXXXXXXX: to=<abc@xyz.localdomain>,
#   orig_to=<test>, relay=mail.gmx.net[x.x.x.x]:25, delay=1,
#   delays=0.02/0.02/0.93/0.06, dsn=5.7.0, status=bounced (host
#   mail.gmx.net[x.x.x.x] said: 550 5.7.0 Sender address does not belong to
#   logged in user {mp030} (in reply to MAIL FROM command))
xmlstarlet sel -t \
  -i "//system/email/enable[. = '1']" \
	-v "concat('@${fqdn} ',//system/email/sender)" -n \
	-v "concat('\"\" ',//system/email/sender)" \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_POSTFIX_MAIN_SENDER_CANONICAL_MAPS}
chown root:root ${OMV_POSTFIX_MAIN_SENDER_CANONICAL_MAPS}
chmod 0600 ${OMV_POSTFIX_MAIN_SENDER_CANONICAL_MAPS}
postmap ${OMV_POSTFIX_MAIN_SENDER_CANONICAL_MAPS}

# Create the '/etc/postfix/recipient_bcc' configuration file.
xmlstarlet sel -t -m "//system/email" \
  -o "@${fqdn} openmediavault-notification@localhost" -n \
  -i "enable[. = '1'] and string-length(secondaryemail) > 0" \
	  -v "concat(primaryemail,' ',secondaryemail)" \
  -b \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_POSTFIX_MAIN_RECIPIENT_BCC_MAPS}
chown root:root ${OMV_POSTFIX_MAIN_RECIPIENT_BCC_MAPS}
chmod 0600 ${OMV_POSTFIX_MAIN_RECIPIENT_BCC_MAPS}
postmap ${OMV_POSTFIX_MAIN_RECIPIENT_BCC_MAPS}

# Create the '/etc/postfix/smtp_header_checks' configuration file.
cat <<EOF > ${OMV_POSTFIX_MAIN_SMTP_HEADER_CHECKS}
# Append the hostname to the email subject
/^Subject: (.*)/ REPLACE Subject: \${1} [${fqdn}]
EOF
chown root:root ${OMV_POSTFIX_MAIN_SMTP_HEADER_CHECKS}
chmod 0600 ${OMV_POSTFIX_MAIN_SMTP_HEADER_CHECKS}

# Create the '/etc/postfix/transport' configuration file.
cat <<EOF > ${OMV_POSTFIX_MAIN_TRANSPORT_MAPS}
openmediavault-notification@localhost omvnotificationfilter:
EOF
chown root:root ${OMV_POSTFIX_MAIN_TRANSPORT_MAPS}
chmod 0600 ${OMV_POSTFIX_MAIN_TRANSPORT_MAPS}
postmap ${OMV_POSTFIX_MAIN_TRANSPORT_MAPS}

exit 0
