#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2020 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_POSTFIX_CRON_CONFIG=${OMV_POSTFIX_CRON_CONFIG:-"/etc/cron.hourly/openmediavault-flushmailq"}

# Create a hourly cron job that flushes the postfix mail queue if email
# notification is disabled.
if [ "$(omv_config_get "//system/email/enable")" = "0" ]; then
	cat <<EOF > ${OMV_POSTFIX_CRON_CONFIG}
#!/bin/sh
# Flush the mail queue every hour if email notification is disabled.
postsuper -d ALL
EOF
	chmod 750 ${OMV_POSTFIX_CRON_CONFIG}
else
	rm -f ${OMV_POSTFIX_CRON_CONFIG}
fi

exit 0
