#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2015 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_AVAHIDAEMON_SMBSERVICE=${OMV_AVAHIDAEMON_SMBSERVICE:-"/etc/avahi/services/smb.service"}
OMV_AVAHIDAEMON_SMBSERVICE_PORT=${OMV_AVAHIDAEMON_SMBSERVICE_PORT:-"445"}

# Is the service enabled? Announce this service via DNS-SD?
rm -f ${OMV_AVAHIDAEMON_SMBSERVICE}
[ "$(omv_config_get "//services/smb/enable")" != "1" -o "$(omv_config_get "//services/zeroconf/services/service[id='smb']/enable")" != "1" ] && exit 0

# Create '/etc/avahi/services/smb.service' file.
name=$(omv_config_get "//services/zeroconf/services/service[id='smb']/name")
cat <<EOF > ${OMV_AVAHIDAEMON_SMBSERVICE}
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">${name}</name>
  <service>
    <type>_smb._tcp</type>
    <port>${OMV_AVAHIDAEMON_SMBSERVICE_PORT}</port>
  </service>
</service-group>
EOF
