#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2011 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
	configure)
		# Create the configuration files
		${OMV_SCRIPTS_DIR}/transmissionbt
		# Enable/disable service
		if [ "$(omv_config_get "//services/transmissionbt/enable")" = "0" ]; then
			update-rc.d -f transmission-daemon remove
		else
			update-rc.d transmission-daemon start 20 2 3 4 5 . stop 20 0 1 6 .
		fi
	;;

	*)
		echo "$(basename $0) called with unknown argument '$1'" >&2
		exit 1
	;;
esac

exit 0
