#!/bin/sh

set -e

case "$1" in
	configure)
		if ! getent passwd shairport >/dev/null 2>&1; then
			adduser --quiet --system --home /var/lib/shairport --no-create-home shairport
		fi
		if [ -x "/etc/init.d/shairport" ]; then
			update-rc.d shairport defaults 25 >/dev/null
			invoke-rc.d shairport start || exit $?
		fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)
		;;

	*)
		echo "postinst called with unknown argument '$1'" >&2
		exit 1
		;;
esac

exit 0
