#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2023 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Restart `omv-engined` to prevent errors like:
# omv-engined[66400]: PAM unable to dlopen(pam_faillock.so): /lib/security/pam_faillock.so: cannot open shared object file: No such file or directory
# omv-engined[66400]: PAM adding faulty module: pam_faillock.so
# omv-engined[66400]: PAM unable to dlopen(pam_unix.so): /lib/security/pam_unix.so: cannot open shared object file: No such file or directory
# omv-engined[66400]: PAM adding faulty module: pam_unix.so
# omv-engined[66400]: PAM unable to dlopen(pam_systemd.so): /lib/security/pam_systemd.so: cannot open shared object file: No such file or directory
# omv-engined[66400]: PAM adding faulty module: pam_systemd.so
monit restart omv-engined || :

exit 0
